import { Equipment } from './types';

export const INITIAL_EQUIPMENT: Equipment[] = [
  // 1. Electric Forklift FL-07 (Maintenance Due)
  {
    id: 'eq-201',
    equipmentId: 'FL-07',
    name: 'Electric Forklift FL-07',
    type: 'Forklift',
    zone: 'Dock Bay 04',
    condition: 'Fair',
    status: 'MAINTENANCE DUE',
    utilizationPercent: 88,
    lastMaintenanceDate: '2026-01-10',
    nextMaintenanceDate: '2026-02-20',
    maintenanceCostInr: 18500,
    backupAvailableId: 'eq-203',
    backupAvailableName: 'Forklift FL-03 Available (Dock Bay 01)',
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Outbound Staging Bay 04',
    notes: 'Exceeded recommended 250-hour hydraulic service interval. Muthu recommends scheduling night shift service and deploying FL-03.'
  },
  // 2. Main Sortation Conveyor CV-02 (Operational)
  {
    id: 'eq-202',
    equipmentId: 'CV-02',
    name: 'Main Sortation Conveyor CV-02',
    type: 'Conveyor System',
    zone: 'Zone B (Electronics)',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 94,
    lastMaintenanceDate: '2026-02-01',
    nextMaintenanceDate: '2026-03-01',
    maintenanceCostInr: 32000,
    backupAvailableId: 'eq-211',
    backupAvailableName: 'Bypass Chute CV-02B Available',
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Zone B Sorting Line 2',
    notes: 'Belt alignment verified during morning shift start.'
  },
  // 3. Electric Forklift FL-03 (Backup Available / Operational)
  {
    id: 'eq-203',
    equipmentId: 'FL-03',
    name: 'Electric Forklift FL-03 (Standby Backup)',
    type: 'Forklift',
    zone: 'Dock Bay 01',
    condition: 'Excellent',
    status: 'OPERATIONAL',
    utilizationPercent: 35,
    lastMaintenanceDate: '2026-02-12',
    nextMaintenanceDate: '2026-03-20',
    maintenanceCostInr: 8000,
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Reserve Equipment Bay 01',
    notes: 'Fully charged backup forklift ready for immediate deployment when FL-07 undergoes servicing.'
  },
  // 4. High-Speed Automated Sorter AS-01 (Operational)
  {
    id: 'eq-204',
    equipmentId: 'AS-01',
    name: 'High-Speed Automated Sorter AS-01',
    type: 'Automated Sorter',
    zone: 'Mezzanine',
    condition: 'Excellent',
    status: 'OPERATIONAL',
    utilizationPercent: 91,
    lastMaintenanceDate: '2026-02-05',
    nextMaintenanceDate: '2026-03-15',
    maintenanceCostInr: 45000,
    backupAvailableId: 'eq-202',
    backupAvailableName: 'Conveyor CV-02 Routing Bypass Available',
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Mezzanine Hub Sortation Core',
    notes: 'Processes up to 2,400 parcels/hour.'
  },
  // 5. Automatic Box Sealing Machine PM-02 (Under Maintenance)
  {
    id: 'eq-205',
    equipmentId: 'PM-02',
    name: 'Automatic Box Sealing Machine PM-02',
    type: 'Packing Machine',
    zone: 'Zone C (Packaging)',
    condition: 'Poor',
    status: 'UNDER MAINTENANCE',
    utilizationPercent: 0,
    lastMaintenanceDate: '2026-02-17',
    nextMaintenanceDate: '2026-02-19',
    maintenanceCostInr: 22000,
    backupAvailableId: 'eq-206',
    backupAvailableName: 'Packing Machine PM-01 Available (Station 1)',
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Packing Station 2',
    notes: 'Tape dispenser jam cleared; motor heating sensor calibration ongoing.'
  },
  // 6. Automatic Box Sealing Machine PM-01 (Operational)
  {
    id: 'eq-206',
    equipmentId: 'PM-01',
    name: 'Automatic Box Sealing Machine PM-01',
    type: 'Packing Machine',
    zone: 'Zone A (Furniture)',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 82,
    lastMaintenanceDate: '2026-01-25',
    nextMaintenanceDate: '2026-02-28',
    maintenanceCostInr: 12000,
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Packing Station 1',
    notes: 'Operating smoothly at 45 boxes/min throughput.'
  },
  // 7. Heavy Overhead Crane CR-01 (Operational)
  {
    id: 'eq-207',
    equipmentId: 'CR-01',
    name: 'Heavy Overhead Crane CR-01',
    type: 'Crane',
    zone: 'Zone A (Furniture)',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 62,
    lastMaintenanceDate: '2026-01-15',
    nextMaintenanceDate: '2026-03-01',
    maintenanceCostInr: 55000,
    backupAvailableId: 'eq-212',
    backupAvailableName: 'Overhead Hoist Crane CR-02 Available',
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Heavy Wood Pallet Staging Zone',
    notes: 'Rated for 3.5 ton pallet lifts.'
  },
  // 8. Industrial Scanner Array BS-04 (Warning)
  {
    id: 'eq-208',
    equipmentId: 'BS-04',
    name: 'Industrial Scanner Array BS-04',
    type: 'Barcode Scanner',
    zone: 'Zone B (Electronics)',
    condition: 'Fair',
    status: 'WARNING',
    utilizationPercent: 96,
    lastMaintenanceDate: '2025-12-20',
    nextMaintenanceDate: '2026-02-22',
    maintenanceCostInr: 6500,
    backupAvailableId: 'eq-213',
    backupAvailableName: 'Handheld Bluetooth Scanner BS-02 Available',
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Scan Tunnel 4',
    notes: 'Lens dust accumulation causing 3% scan retry rate. Optical wipe cleaning required.'
  },
  // 9. Autonomous AGV Robot RB-01 (Operational)
  {
    id: 'eq-209',
    equipmentId: 'RB-01',
    name: 'Autonomous AGV Robot RB-01',
    type: 'Warehouse Robot',
    zone: 'Mezzanine',
    condition: 'Excellent',
    status: 'OPERATIONAL',
    utilizationPercent: 87,
    lastMaintenanceDate: '2026-02-08',
    nextMaintenanceDate: '2026-03-08',
    maintenanceCostInr: 28000,
    backupAvailableId: 'eq-210',
    backupAvailableName: 'AGV Robot RB-02 Available',
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Tote Transport Grid 1',
    notes: 'Transports tote bins between Mezzanine picking and Zone B sorting lines.'
  },
  // 10. Autonomous AGV Robot RB-02 (Operational / Standby)
  {
    id: 'eq-210',
    equipmentId: 'RB-02',
    name: 'Autonomous AGV Robot RB-02',
    type: 'Warehouse Robot',
    zone: 'Mezzanine',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 40,
    lastMaintenanceDate: '2026-02-08',
    nextMaintenanceDate: '2026-03-08',
    maintenanceCostInr: 15000,
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Tote Transport Grid 2',
    notes: 'Standby tote transport AGV on dock charge.'
  },
  // 11. Pallet Jack Hydraulic PJ-01 (Operational)
  {
    id: 'eq-211',
    equipmentId: 'PJ-01',
    name: 'Heavy Duty Pallet Jack PJ-01',
    type: 'Pallet Jack',
    zone: 'Dock Bay',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 78,
    lastMaintenanceDate: '2026-01-30',
    nextMaintenanceDate: '2026-03-10',
    maintenanceCostInr: 4500,
    backupAvailableId: 'eq-214',
    backupAvailableName: 'Pallet Jack PJ-02 Available',
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Outbound Bay 2 & 3',
    notes: 'Hydraulic seals pressure checked.'
  },
  // 12. Heavy Overhead Crane CR-02 (Operational)
  {
    id: 'eq-212',
    equipmentId: 'CR-02',
    name: 'Overhead Gantry Hoist CR-02',
    type: 'Crane',
    zone: 'Zone A (Furniture)',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 45,
    lastMaintenanceDate: '2026-01-18',
    nextMaintenanceDate: '2026-03-15',
    maintenanceCostInr: 38000,
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Zone A Pallet Rack High-Bay',
    notes: 'Secondary gantry crane for oversized furniture pallets.'
  },
  // 13. Handheld Scanner BS-02 (Operational)
  {
    id: 'eq-213',
    equipmentId: 'BS-02',
    name: 'Handheld Bluetooth Scanner BS-02',
    type: 'Barcode Scanner',
    zone: 'Zone B (Electronics)',
    condition: 'Excellent',
    status: 'OPERATIONAL',
    utilizationPercent: 65,
    lastMaintenanceDate: '2026-02-10',
    nextMaintenanceDate: '2026-04-10',
    maintenanceCostInr: 2500,
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'QC Station Charging Dock',
    notes: 'Ruggedized scanner with long battery life.'
  },
  // 14. Hydraulic Pallet Jack PJ-02 (Operational)
  {
    id: 'eq-214',
    equipmentId: 'PJ-02',
    name: 'Heavy Duty Pallet Jack PJ-02',
    type: 'Pallet Jack',
    zone: 'Dock Bay',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 55,
    lastMaintenanceDate: '2026-01-20',
    nextMaintenanceDate: '2026-03-05',
    maintenanceCostInr: 4000,
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Inbound Receiving Bay',
    notes: 'Ready for loading support.'
  },
  // 15. Hydraulic Dock Leveler LE-01 (Operational)
  {
    id: 'eq-215',
    equipmentId: 'LE-01',
    name: 'Hydraulic Dock Leveler LE-01',
    type: 'Loading Equipment',
    zone: 'Dock Bay',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 84,
    lastMaintenanceDate: '2026-01-28',
    nextMaintenanceDate: '2026-02-28',
    maintenanceCostInr: 16000,
    backupAvailableId: 'eq-216',
    backupAvailableName: 'Dock Leveler LE-02 Available (Dock 5)',
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Dock Bay 04 Ramp',
    notes: 'Lip hinge greased and hydraulic pump tested.'
  },
  // 16. Hydraulic Dock Leveler LE-02 (Operational)
  {
    id: 'eq-216',
    equipmentId: 'LE-02',
    name: 'Hydraulic Dock Leveler LE-02',
    type: 'Loading Equipment',
    zone: 'Dock Bay',
    condition: 'Excellent',
    status: 'OPERATIONAL',
    utilizationPercent: 60,
    lastMaintenanceDate: '2026-02-02',
    nextMaintenanceDate: '2026-03-15',
    maintenanceCostInr: 14000,
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Dock Bay 05 Ramp',
    notes: 'Secondary truck loading bridge ramp.'
  },
  // 17. Electric Forklift FL-01 (Operational)
  {
    id: 'eq-217',
    equipmentId: 'FL-01',
    name: 'Heavy Mast Forklift FL-01',
    type: 'Forklift',
    zone: 'Zone A (Furniture)',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 86,
    lastMaintenanceDate: '2026-01-22',
    nextMaintenanceDate: '2026-03-01',
    maintenanceCostInr: 21000,
    backupAvailableId: 'eq-203',
    backupAvailableName: 'Forklift FL-03 Available',
    assignedTechnicianName: 'Kiran Naik',
    locationDetails: 'Zone A High Bay Aisle 1',
    notes: '3-stage mast for 8-meter vertical rack storage.'
  },
  // 18. Conveyor Feeder System CV-01 (Operational)
  {
    id: 'eq-218',
    equipmentId: 'CV-01',
    name: 'Inbound Feeder Conveyor CV-01',
    type: 'Conveyor System',
    zone: 'Dock Bay',
    condition: 'Good',
    status: 'OPERATIONAL',
    utilizationPercent: 79,
    lastMaintenanceDate: '2026-01-20',
    nextMaintenanceDate: '2026-03-05',
    maintenanceCostInr: 26000,
    assignedTechnicianName: 'Sandeep Mukherjee',
    locationDetails: 'Inbound De-palletizing Line',
    notes: 'Transports inbound cartons to sortation core.'
  }
];
