import { InventoryItem, InventoryStatus, ProductCategory, AIPredictionType } from './types';

export function calculateStockStatus(
  quantityAvailable: number,
  reorderLevel: number,
  maxStock: number
): InventoryStatus {
  if (quantityAvailable <= 0) {
    return 'Out of Stock';
  }
  if (quantityAvailable <= Math.max(1, Math.round(reorderLevel * 0.45))) {
    return 'Critical';
  }
  if (quantityAvailable <= reorderLevel) {
    return 'Low Stock';
  }
  if (quantityAvailable > Math.round(maxStock * 0.92)) {
    return 'Oversupplied';
  }
  return 'Optimal';
}

export function computeStockPercentage(quantityAvailable: number, maxStock: number): number {
  if (!maxStock || maxStock <= 0) return 0;
  return Math.min(100, Math.max(0, Math.round((quantityAvailable / maxStock) * 100)));
}

interface RawProductData {
  id: string;
  sku: string;
  name: string;
  category: ProductCategory;
  quantityAvailable: number;
  reservedQuantity: number;
  damagedQuantity: number;
  reorderLevel: number;
  maxStock: number;
  warehouseZone: string;
  shelfBinLocation: string;
  supplier: string;
  unitPrice: number;
  aiPrediction: string;
  aiPredictionType: AIPredictionType;
  icon: string;
  lastRestocked: string;
  leadTimeDays: number;
}

const rawProductsList: RawProductData[] = [
  // ===================== ELECTRONICS (25 Products) =====================
  {
    id: 'PRD-1001',
    sku: 'SKU-ELC-1001',
    name: 'ProBook 15" Enterprise Workstation',
    category: 'Electronics',
    quantityAvailable: 14,
    reservedQuantity: 12,
    damagedQuantity: 1,
    reorderLevel: 25,
    maxStock: 150,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-02-04-A',
    supplier: 'Silicon Dynamics',
    unitPrice: 890.00,
    aiPrediction: 'Depletion in 2 Days',
    aiPredictionType: 'depletion',
    icon: 'laptop_mac',
    lastRestocked: '2026-08-02',
    leadTimeDays: 5
  },
  {
    id: 'PRD-1002',
    sku: 'SKU-ELC-1002',
    name: 'UltraWide 34" Curved IPS Monitor',
    category: 'Electronics',
    quantityAvailable: 86,
    reservedQuantity: 14,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-03-01-C',
    supplier: 'ViewMaster Displays',
    unitPrice: 420.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'desktop_windows',
    lastRestocked: '2026-08-11',
    leadTimeDays: 4
  },
  {
    id: 'PRD-1003',
    sku: 'SKU-ELC-1003',
    name: 'Industrial High-Speed Thermal Printer',
    category: 'Electronics',
    quantityAvailable: 8,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 10,
    maxStock: 12,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-04-02-B',
    supplier: 'ZebraTech Supply',
    unitPrice: 450.00,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'print',
    lastRestocked: '2026-07-28',
    leadTimeDays: 7
  },
  {
    id: 'PRD-1004',
    sku: 'SKU-ELC-1004',
    name: 'Rugged Wireless 2D Barcode Scanner',
    category: 'Electronics',
    quantityAvailable: 34,
    reservedQuantity: 6,
    damagedQuantity: 2,
    reorderLevel: 20,
    maxStock: 60,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-01-03-A',
    supplier: 'ZebraTech Supply',
    unitPrice: 165.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'qr_code_scanner',
    lastRestocked: '2026-08-09',
    leadTimeDays: 3
  },
  {
    id: 'PRD-1005',
    sku: 'SKU-ELC-1005',
    name: 'Thunderbolt 4 Universal Dual-4K Dock',
    category: 'Electronics',
    quantityAvailable: 4,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 100,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-05-01-A',
    supplier: 'LogiPro Components',
    unitPrice: 195.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'hub',
    lastRestocked: '2026-07-15',
    leadTimeDays: 3
  },
  {
    id: 'PRD-1006',
    sku: 'SKU-ELC-1006',
    name: 'Active Noise Cancelling Headset Pro',
    category: 'Electronics',
    quantityAvailable: 110,
    reservedQuantity: 18,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 180,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-02-01-D',
    supplier: 'Acoustic Labs Inc',
    unitPrice: 135.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'headphones',
    lastRestocked: '2026-08-12',
    leadTimeDays: 4
  },
  {
    id: 'PRD-1007',
    sku: 'SKU-ELC-1007',
    name: 'Tactile Mechanical Keyboard RGB',
    category: 'Electronics',
    quantityAvailable: 78,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 35,
    maxStock: 150,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-06-03-B',
    supplier: 'LogiPro Components',
    unitPrice: 89.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'keyboard',
    lastRestocked: '2026-08-07',
    leadTimeDays: 5
  },
  {
    id: 'PRD-1008',
    sku: 'SKU-ELC-1008',
    name: 'Precision Wireless Ergonomic Mouse',
    category: 'Electronics',
    quantityAvailable: 95,
    reservedQuantity: 22,
    damagedQuantity: 3,
    reorderLevel: 50,
    maxStock: 220,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-06-02-A',
    supplier: 'LogiPro Components',
    unitPrice: 59.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'mouse',
    lastRestocked: '2026-08-10',
    leadTimeDays: 3
  },
  {
    id: 'PRD-1009',
    sku: 'SKU-ELC-1009',
    name: '4K Ultra-HD Conference Room Webcam',
    category: 'Electronics',
    quantityAvailable: 3,
    reservedQuantity: 5,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 80,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-04-03-D',
    supplier: 'Silicon Dynamics',
    unitPrice: 220.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'videocam',
    lastRestocked: '2026-07-20',
    leadTimeDays: 6
  },
  {
    id: 'PRD-1010',
    sku: 'SKU-ELC-1010',
    name: 'Gigabit 24-Port Managed PoE Switch',
    category: 'Electronics',
    quantityAvailable: 19,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 40,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-08-01-A',
    supplier: 'Netlink Infrastructure',
    unitPrice: 340.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'router',
    lastRestocked: '2026-08-04',
    leadTimeDays: 7
  },
  {
    id: 'PRD-1011',
    sku: 'SKU-ELC-1011',
    name: 'Enterprise NVMe SSD 2TB M.2',
    category: 'Electronics',
    quantityAvailable: 140,
    reservedQuantity: 30,
    damagedQuantity: 2,
    reorderLevel: 60,
    maxStock: 300,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-09-02-C',
    supplier: 'Silicon Dynamics',
    unitPrice: 175.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'storage',
    lastRestocked: '2026-08-14',
    leadTimeDays: 3
  },
  {
    id: 'PRD-1012',
    sku: 'SKU-ELC-1012',
    name: 'Warehouse RFID Mobile Terminal Handheld',
    category: 'Electronics',
    quantityAvailable: 0,
    reservedQuantity: 0,
    damagedQuantity: 1,
    reorderLevel: 8,
    maxStock: 35,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-01-01-A',
    supplier: 'ZebraTech Supply',
    unitPrice: 620.00,
    aiPrediction: 'Dead Stock Risk',
    aiPredictionType: 'dead_stock',
    icon: 'point_of_sale',
    lastRestocked: '2026-06-18',
    leadTimeDays: 10
  },
  {
    id: 'PRD-1013',
    sku: 'SKU-ELC-1013',
    name: '10.5" Rugged Warehouse Tablet',
    category: 'Electronics',
    quantityAvailable: 22,
    reservedQuantity: 5,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 50,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-03-04-B',
    supplier: 'Silicon Dynamics',
    unitPrice: 510.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'tablet_android',
    lastRestocked: '2026-08-01',
    leadTimeDays: 6
  },
  {
    id: 'PRD-1014',
    sku: 'SKU-ELC-1014',
    name: 'Smart Bluetooth Label Applicator Tool',
    category: 'Electronics',
    quantityAvailable: 6,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 12,
    maxStock: 40,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-04-01-C',
    supplier: 'ZebraTech Supply',
    unitPrice: 280.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'label',
    lastRestocked: '2026-07-29',
    leadTimeDays: 4
  },
  {
    id: 'PRD-1015',
    sku: 'SKU-ELC-1015',
    name: '100W GaN Fast Charger 4-Port',
    category: 'Electronics',
    quantityAvailable: 210,
    reservedQuantity: 45,
    damagedQuantity: 4,
    reorderLevel: 80,
    maxStock: 400,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-07-02-D',
    supplier: 'LogiPro Components',
    unitPrice: 42.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'power',
    lastRestocked: '2026-08-13',
    leadTimeDays: 2
  },
  {
    id: 'PRD-1016',
    sku: 'SKU-ELC-1016',
    name: 'Uninterruptible Power Supply (UPS) 1500VA',
    category: 'Electronics',
    quantityAvailable: 11,
    reservedQuantity: 3,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 30,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-08-04-A',
    supplier: 'Netlink Infrastructure',
    unitPrice: 260.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'battery_charging_full',
    lastRestocked: '2026-07-26',
    leadTimeDays: 8
  },
  {
    id: 'PRD-1017',
    sku: 'SKU-ELC-1017',
    name: 'Biometric Time Attendance Clock Terminal',
    category: 'Electronics',
    quantityAvailable: 15,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 8,
    maxStock: 20,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-05-03-A',
    supplier: 'SecureTech Systems',
    unitPrice: 310.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'fingerprint',
    lastRestocked: '2026-08-05',
    leadTimeDays: 5
  },
  {
    id: 'PRD-1018',
    sku: 'SKU-ELC-1018',
    name: 'Wi-Fi 6E Mesh Access Point Dual-Band',
    category: 'Electronics',
    quantityAvailable: 38,
    reservedQuantity: 8,
    damagedQuantity: 1,
    reorderLevel: 25,
    maxStock: 90,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-07-04-B',
    supplier: 'Netlink Infrastructure',
    unitPrice: 185.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'wifi',
    lastRestocked: '2026-08-08',
    leadTimeDays: 4
  },
  {
    id: 'PRD-1019',
    sku: 'SKU-ELC-1019',
    name: 'Digital Caliper 150mm Stainless Steel',
    category: 'Electronics',
    quantityAvailable: 65,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 70,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-06-01-D',
    supplier: 'Apex Office Essentials',
    unitPrice: 34.50,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'straighten',
    lastRestocked: '2026-08-11',
    leadTimeDays: 3
  },
  {
    id: 'PRD-1020',
    sku: 'SKU-ELC-1020',
    name: 'High-Torque Electric Screwdriver Kit',
    category: 'Electronics',
    quantityAvailable: 42,
    reservedQuantity: 6,
    damagedQuantity: 1,
    reorderLevel: 25,
    maxStock: 100,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-09-01-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 75.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'construction',
    lastRestocked: '2026-08-06',
    leadTimeDays: 4
  },
  {
    id: 'PRD-1021',
    sku: 'SKU-ELC-1021',
    name: '4K DisplayPort to HDMI 2.1 Adapter 6ft',
    category: 'Electronics',
    quantityAvailable: 320,
    reservedQuantity: 40,
    damagedQuantity: 6,
    reorderLevel: 100,
    maxStock: 600,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-05-04-C',
    supplier: 'LogiPro Components',
    unitPrice: 18.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'cable',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },
  {
    id: 'PRD-1022',
    sku: 'SKU-ELC-1022',
    name: 'Cat6A Shielded Ethernet Cable (1000ft Roll)',
    category: 'Electronics',
    quantityAvailable: 18,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 45,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-08-02-D',
    supplier: 'Netlink Infrastructure',
    unitPrice: 145.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'settings_ethernet',
    lastRestocked: '2026-08-03',
    leadTimeDays: 5
  },
  {
    id: 'PRD-1023',
    sku: 'SKU-ELC-1023',
    name: 'Bluetooth Asset Tracking Beacons (Pack of 20)',
    category: 'Electronics',
    quantityAvailable: 2,
    reservedQuantity: 1,
    damagedQuantity: 0,
    reorderLevel: 10,
    maxStock: 50,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-01-04-A',
    supplier: 'SecureTech Systems',
    unitPrice: 180.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'location_searching',
    lastRestocked: '2026-07-22',
    leadTimeDays: 6
  },
  {
    id: 'PRD-1024',
    sku: 'SKU-ELC-1024',
    name: 'Compact Thermal Shipping Receipt Printer',
    category: 'Electronics',
    quantityAvailable: 28,
    reservedQuantity: 5,
    damagedQuantity: 1,
    reorderLevel: 15,
    maxStock: 50,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-04-04-A',
    supplier: 'ZebraTech Supply',
    unitPrice: 210.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'receipt',
    lastRestocked: '2026-08-07',
    leadTimeDays: 4
  },
  {
    id: 'PRD-1025',
    sku: 'SKU-ELC-1025',
    name: 'Micro-SDXC 128GB High Endurance Card',
    category: 'Electronics',
    quantityAvailable: 410,
    reservedQuantity: 60,
    damagedQuantity: 2,
    reorderLevel: 150,
    maxStock: 800,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-09-03-A',
    supplier: 'Silicon Dynamics',
    unitPrice: 24.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'sd_card',
    lastRestocked: '2026-08-14',
    leadTimeDays: 2
  },

  // ===================== FURNITURE (20 Products) =====================
  {
    id: 'PRD-2001',
    sku: 'SKU-FUR-2001',
    name: 'Ergonomic Breathable Mesh Task Chair',
    category: 'Furniture',
    quantityAvailable: 450,
    reservedQuantity: 32,
    damagedQuantity: 4,
    reorderLevel: 100,
    maxStock: 500,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-14-01-A',
    supplier: 'ErgoForm Living',
    unitPrice: 145.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'chair',
    lastRestocked: '2026-08-10',
    leadTimeDays: 5
  },
  {
    id: 'PRD-2002',
    sku: 'SKU-FUR-2002',
    name: 'Electric Dual-Motor Standing Desk Frame 60x30',
    category: 'Furniture',
    quantityAvailable: 68,
    reservedQuantity: 18,
    damagedQuantity: 1,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-12-02-B',
    supplier: 'ErgoForm Living',
    unitPrice: 320.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'table_restaurant',
    lastRestocked: '2026-08-08',
    leadTimeDays: 6
  },
  {
    id: 'PRD-2003',
    sku: 'SKU-FUR-2003',
    name: 'Heavy Duty 5-Tier Industrial Steel Shelving Unit',
    category: 'Furniture',
    quantityAvailable: 38,
    reservedQuantity: 6,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 80,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-18-01-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 215.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'shelves',
    lastRestocked: '2026-08-05',
    leadTimeDays: 7
  },
  {
    id: 'PRD-2004',
    sku: 'SKU-FUR-2004',
    name: 'High-Density Anti-Fatigue Floor Mat 36x24',
    category: 'Furniture',
    quantityAvailable: 12,
    reservedQuantity: 8,
    damagedQuantity: 1,
    reorderLevel: 30,
    maxStock: 150,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-08-03-C',
    supplier: 'ComfortMat Pro',
    unitPrice: 48.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'crop_landscape',
    lastRestocked: '2026-07-25',
    leadTimeDays: 3
  },
  {
    id: 'PRD-2005',
    sku: 'SKU-FUR-2005',
    name: 'Mobile Under-Desk 3-Drawer Steel Filing Cabinet',
    category: 'Furniture',
    quantityAvailable: 42,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 90,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-10-02-D',
    supplier: 'ErgoForm Living',
    unitPrice: 110.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'inventory',
    lastRestocked: '2026-08-04',
    leadTimeDays: 5
  },
  {
    id: 'PRD-2006',
    sku: 'SKU-FUR-2006',
    name: 'Executive Leatherette Swivel Armchair',
    category: 'Furniture',
    quantityAvailable: 5,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 60,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-15-01-B',
    supplier: 'ErgoForm Living',
    unitPrice: 280.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'chair_alt',
    lastRestocked: '2026-07-28',
    leadTimeDays: 6
  },
  {
    id: 'PRD-2007',
    sku: 'SKU-FUR-2007',
    name: 'Modular Acoustic Desk Privacy Screen 48"',
    category: 'Furniture',
    quantityAvailable: 74,
    reservedQuantity: 14,
    damagedQuantity: 1,
    reorderLevel: 30,
    maxStock: 100,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-06-02-A',
    supplier: 'ComfortMat Pro',
    unitPrice: 85.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'border_all',
    lastRestocked: '2026-08-09',
    leadTimeDays: 4
  },
  {
    id: 'PRD-2008',
    sku: 'SKU-FUR-2008',
    name: 'Adjustable Drafting Stool with Foot Ring',
    category: 'Furniture',
    quantityAvailable: 55,
    reservedQuantity: 8,
    damagedQuantity: 2,
    reorderLevel: 25,
    maxStock: 110,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-13-03-C',
    supplier: 'ErgoForm Living',
    unitPrice: 125.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'chair',
    lastRestocked: '2026-08-06',
    leadTimeDays: 5
  },
  {
    id: 'PRD-2009',
    sku: 'SKU-FUR-2009',
    name: 'Heavy Duty Steel Warehouse Workstation 72x36',
    category: 'Furniture',
    quantityAvailable: 16,
    reservedQuantity: 3,
    damagedQuantity: 0,
    reorderLevel: 10,
    maxStock: 25,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-20-01-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 480.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'table_bar',
    lastRestocked: '2026-08-01',
    leadTimeDays: 8
  },
  {
    id: 'PRD-2010',
    sku: 'SKU-FUR-2010',
    name: 'Wall-Mount Steel First Aid Cabinet (Large)',
    category: 'Furniture',
    quantityAvailable: 31,
    reservedQuantity: 5,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 50,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-02-01-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 95.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'medical_services',
    lastRestocked: '2026-08-07',
    leadTimeDays: 4
  },
  {
    id: 'PRD-2011',
    sku: 'SKU-FUR-2011',
    name: 'Stackable Poly Conference Chairs (Set of 4)',
    category: 'Furniture',
    quantityAvailable: 88,
    reservedQuantity: 16,
    damagedQuantity: 3,
    reorderLevel: 40,
    maxStock: 90,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-16-02-D',
    supplier: 'ErgoForm Living',
    unitPrice: 190.00,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'event_seat',
    lastRestocked: '2026-08-12',
    leadTimeDays: 5
  },
  {
    id: 'PRD-2012',
    sku: 'SKU-FUR-2012',
    name: 'Heavy-Duty 2-Door Lockable Metal Storage Locker',
    category: 'Furniture',
    quantityAvailable: 19,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 12,
    maxStock: 35,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-19-03-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 340.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'lock',
    lastRestocked: '2026-07-30',
    leadTimeDays: 7
  },
  {
    id: 'PRD-2013',
    sku: 'SKU-FUR-2013',
    name: 'Rolling Mobile Whiteboard 72x48 Double Sided',
    category: 'Furniture',
    quantityAvailable: 24,
    reservedQuantity: 4,
    damagedQuantity: 1,
    reorderLevel: 15,
    maxStock: 40,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-05-02-C',
    supplier: 'Apex Office Essentials',
    unitPrice: 175.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'view_kanban',
    lastRestocked: '2026-08-03',
    leadTimeDays: 4
  },
  {
    id: 'PRD-2014',
    sku: 'SKU-FUR-2014',
    name: 'Under-Desk Steel CPU Holder Mount Bracket',
    category: 'Furniture',
    quantityAvailable: 62,
    reservedQuantity: 12,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 100,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-07-01-B',
    supplier: 'ErgoForm Living',
    unitPrice: 36.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'developer_board',
    lastRestocked: '2026-08-11',
    leadTimeDays: 3
  },
  {
    id: 'PRD-2015',
    sku: 'SKU-FUR-2015',
    name: 'Mesh Footrest with Rocking Massage Rollers',
    category: 'Furniture',
    quantityAvailable: 85,
    reservedQuantity: 15,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 140,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-09-04-A',
    supplier: 'ComfortMat Pro',
    unitPrice: 29.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'pan_tool_alt',
    lastRestocked: '2026-08-08',
    leadTimeDays: 3
  },
  {
    id: 'PRD-2016',
    sku: 'SKU-FUR-2016',
    name: 'Heavy Duty 300lb Capacity Folding Utility Cart',
    category: 'Furniture',
    quantityAvailable: 0,
    reservedQuantity: 0,
    damagedQuantity: 2,
    reorderLevel: 10,
    maxStock: 30,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-01-02-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 120.00,
    aiPrediction: 'Dead Stock Risk',
    aiPredictionType: 'dead_stock',
    icon: 'shopping_cart',
    lastRestocked: '2026-06-15',
    leadTimeDays: 6
  },
  {
    id: 'PRD-2017',
    sku: 'SKU-FUR-2017',
    name: 'Ergonomic Kneeling Posture Stool Wood Frame',
    category: 'Furniture',
    quantityAvailable: 14,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 45,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-11-01-C',
    supplier: 'ErgoForm Living',
    unitPrice: 110.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'self_improvement',
    lastRestocked: '2026-07-24',
    leadTimeDays: 5
  },
  {
    id: 'PRD-2018',
    sku: 'SKU-FUR-2018',
    name: 'Acoustic Sound Dampening Baffle Ceiling Panel',
    category: 'Furniture',
    quantityAvailable: 48,
    reservedQuantity: 12,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 75,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-04-03-B',
    supplier: 'ComfortMat Pro',
    unitPrice: 65.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'volume_down',
    lastRestocked: '2026-08-02',
    leadTimeDays: 5
  },
  {
    id: 'PRD-2019',
    sku: 'SKU-FUR-2019',
    name: 'Heavy Duty Cantilever Racking Arm (Pair)',
    category: 'Furniture',
    quantityAvailable: 22,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 50,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-21-02-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 160.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'warehouse',
    lastRestocked: '2026-07-31',
    leadTimeDays: 7
  },
  {
    id: 'PRD-2020',
    sku: 'SKU-FUR-2020',
    name: 'Wire Mesh Cable Management J-Channel Tray',
    category: 'Furniture',
    quantityAvailable: 195,
    reservedQuantity: 30,
    damagedQuantity: 2,
    reorderLevel: 60,
    maxStock: 250,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-07-03-A',
    supplier: 'ErgoForm Living',
    unitPrice: 19.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'cable',
    lastRestocked: '2026-08-10',
    leadTimeDays: 3
  },

  // ===================== PACKAGING (25 Products) =====================
  {
    id: 'PRD-3001',
    sku: 'SKU-PKG-3001',
    name: 'Corrugated Shipping Boxes Large 18x14x12 (Bundle 25)',
    category: 'Packaging',
    quantityAvailable: 850,
    reservedQuantity: 120,
    damagedQuantity: 8,
    reorderLevel: 250,
    maxStock: 1000,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-04-01-A',
    supplier: 'EcoPack Global',
    unitPrice: 28.50,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'inventory_2',
    lastRestocked: '2026-08-08',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3002',
    sku: 'SKU-PKG-3002',
    name: 'Corrugated Shipping Boxes Medium 12x9x6 (Bundle 25)',
    category: 'Packaging',
    quantityAvailable: 34,
    reservedQuantity: 60,
    damagedQuantity: 5,
    reorderLevel: 150,
    maxStock: 800,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-04-02-B',
    supplier: 'EcoPack Global',
    unitPrice: 18.00,
    aiPrediction: 'Depletion in 2 Days',
    aiPredictionType: 'depletion',
    icon: 'inventory_2',
    lastRestocked: '2026-07-22',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3003',
    sku: 'SKU-PKG-3003',
    name: 'Heavy Duty Pallet Stretch Film Wrap 80 Gauge (4pk)',
    category: 'Packaging',
    quantityAvailable: 15,
    reservedQuantity: 10,
    damagedQuantity: 1,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-08-01-A',
    supplier: 'EcoPack Global',
    unitPrice: 62.00,
    aiPrediction: 'Depletion in 2 Days',
    aiPredictionType: 'depletion',
    icon: 'layers',
    lastRestocked: '2026-07-26',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3004',
    sku: 'SKU-PKG-3004',
    name: 'Thermal Direct Fanfold Shipping Labels 4x6 (2000ct)',
    category: 'Packaging',
    quantityAvailable: 180,
    reservedQuantity: 40,
    damagedQuantity: 2,
    reorderLevel: 75,
    maxStock: 300,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-02-03-A',
    supplier: 'ZebraTech Supply',
    unitPrice: 32.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'label',
    lastRestocked: '2026-08-11',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3005',
    sku: 'SKU-PKG-3005',
    name: 'Industrial Acrylic Packing Tape 2" x 110yd (Pack of 36)',
    category: 'Packaging',
    quantityAvailable: 92,
    reservedQuantity: 20,
    damagedQuantity: 0,
    reorderLevel: 40,
    maxStock: 150,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-03-01-D',
    supplier: 'EcoPack Global',
    unitPrice: 54.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'tape',
    lastRestocked: '2026-08-09',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3006',
    sku: 'SKU-PKG-3006',
    name: 'Perforated Bubble Cushioning Roll 3/16" x 350ft',
    category: 'Packaging',
    quantityAvailable: 58,
    reservedQuantity: 12,
    damagedQuantity: 1,
    reorderLevel: 25,
    maxStock: 90,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-06-01-A',
    supplier: 'EcoPack Global',
    unitPrice: 44.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'bubble_chart',
    lastRestocked: '2026-08-07',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3007',
    sku: 'SKU-PKG-3007',
    name: 'Reinforced Water-Activated Kraft Tape 3" x 450ft',
    category: 'Packaging',
    quantityAvailable: 4,
    reservedQuantity: 6,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-03-04-A',
    supplier: 'EcoPack Global',
    unitPrice: 68.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'line_weight',
    lastRestocked: '2026-07-20',
    leadTimeDays: 4
  },
  {
    id: 'PRD-3008',
    sku: 'SKU-PKG-3008',
    name: 'Poly Mailers Self-Seal 10x13 Waterproof (500ct)',
    category: 'Packaging',
    quantityAvailable: 240,
    reservedQuantity: 50,
    damagedQuantity: 2,
    reorderLevel: 100,
    maxStock: 350,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-01-02-C',
    supplier: 'EcoPack Global',
    unitPrice: 38.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'mail',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3009',
    sku: 'SKU-PKG-3009',
    name: 'Kraft Cushioning Dunnage Paper 30lb x 1200ft Roll',
    category: 'Packaging',
    quantityAvailable: 46,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 70,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-05-02-B',
    supplier: 'EcoPack Global',
    unitPrice: 34.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'newspaper',
    lastRestocked: '2026-08-06',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3010',
    sku: 'SKU-PKG-3010',
    name: 'Polyester Strapping Kit 1/2" with Tensioner Tool',
    category: 'Packaging',
    quantityAvailable: 19,
    reservedQuantity: 3,
    damagedQuantity: 0,
    reorderLevel: 12,
    maxStock: 40,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-09-01-D',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 115.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'tune',
    lastRestocked: '2026-08-01',
    leadTimeDays: 5
  },
  {
    id: 'PRD-3011',
    sku: 'SKU-PKG-3011',
    name: 'Corrugated Edge Corner Protectors 2x2x36 (Case 100)',
    category: 'Packaging',
    quantityAvailable: 125,
    reservedQuantity: 20,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 130,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-07-02-A',
    supplier: 'EcoPack Global',
    unitPrice: 42.00,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'crop_square',
    lastRestocked: '2026-08-13',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3012',
    sku: 'SKU-PKG-3012',
    name: 'Anti-Static Pink Bubble Bags 8x10 (Pack of 250)',
    category: 'Packaging',
    quantityAvailable: 88,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 35,
    maxStock: 150,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-06-03-B',
    supplier: 'EcoPack Global',
    unitPrice: 29.90,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'shield',
    lastRestocked: '2026-08-10',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3013',
    sku: 'SKU-PKG-3013',
    name: 'Biodegradable Packing Peanuts 14 cu ft Bag',
    category: 'Packaging',
    quantityAvailable: 8,
    reservedQuantity: 6,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 40,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-10-01-A',
    supplier: 'EcoPack Global',
    unitPrice: 26.50,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'grain',
    lastRestocked: '2026-07-29',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3014',
    sku: 'SKU-PKG-3014',
    name: 'Heavy Duty Pistol Grip Tape Dispenser 2"',
    category: 'Packaging',
    quantityAvailable: 45,
    reservedQuantity: 8,
    damagedQuantity: 1,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-03-02-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 16.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'handyman',
    lastRestocked: '2026-08-04',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3015',
    sku: 'SKU-PKG-3015',
    name: 'Tamper-Evident Security Tape "VOID" 2" x 55yd',
    category: 'Packaging',
    quantityAvailable: 62,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 100,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-03-03-C',
    supplier: 'SecureTech Systems',
    unitPrice: 38.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'lock_person',
    lastRestocked: '2026-08-07',
    leadTimeDays: 4
  },
  {
    id: 'PRD-3016',
    sku: 'SKU-PKG-3016',
    name: 'Fragile Handle With Care Warning Stickers (500ct)',
    category: 'Packaging',
    quantityAvailable: 190,
    reservedQuantity: 30,
    damagedQuantity: 0,
    reorderLevel: 50,
    maxStock: 300,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-02-01-B',
    supplier: 'ZebraTech Supply',
    unitPrice: 14.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'warning',
    lastRestocked: '2026-08-09',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3017',
    sku: 'SKU-PKG-3017',
    name: 'Heavy Duty Telescoping Wardrobe Moving Boxes',
    category: 'Packaging',
    quantityAvailable: 0,
    reservedQuantity: 0,
    damagedQuantity: 0,
    reorderLevel: 10,
    maxStock: 25,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-11-02-A',
    supplier: 'EcoPack Global',
    unitPrice: 35.00,
    aiPrediction: 'Dead Stock Risk',
    aiPredictionType: 'dead_stock',
    icon: 'checkroom',
    lastRestocked: '2026-06-20',
    leadTimeDays: 5
  },
  {
    id: 'PRD-3018',
    sku: 'SKU-PKG-3018',
    name: 'Clear Packing List Enclosed Pouches 4.5x5.5 (1000ct)',
    category: 'Packaging',
    quantityAvailable: 130,
    reservedQuantity: 25,
    damagedQuantity: 0,
    reorderLevel: 50,
    maxStock: 200,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-01-04-A',
    supplier: 'EcoPack Global',
    unitPrice: 24.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'description',
    lastRestocked: '2026-08-11',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3019',
    sku: 'SKU-PKG-3019',
    name: 'Thermal Transfer Resin Ribbon Roll 4.33" x 1476ft',
    category: 'Packaging',
    quantityAvailable: 52,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-02-04-D',
    supplier: 'ZebraTech Supply',
    unitPrice: 28.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'format_paint',
    lastRestocked: '2026-08-05',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3020',
    sku: 'SKU-PKG-3020',
    name: 'Expandable Honeycomb Kraft Paper Wrap 15" x 165ft',
    category: 'Packaging',
    quantityAvailable: 78,
    reservedQuantity: 14,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-05-04-A',
    supplier: 'EcoPack Global',
    unitPrice: 39.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'grid_view',
    lastRestocked: '2026-08-08',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3021',
    sku: 'SKU-PKG-3021',
    name: 'Corrugated Bookfolds Multi-Depth Mailers 12x9',
    category: 'Packaging',
    quantityAvailable: 310,
    reservedQuantity: 40,
    damagedQuantity: 3,
    reorderLevel: 100,
    maxStock: 450,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-04-04-A',
    supplier: 'EcoPack Global',
    unitPrice: 19.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'menu_book',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },
  {
    id: 'PRD-3022',
    sku: 'SKU-PKG-3022',
    name: 'Heavy Duty Steel Strapping Seals 1/2" (1000ct)',
    category: 'Packaging',
    quantityAvailable: 85,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 100,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-09-03-B',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 48.00,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'token',
    lastRestocked: '2026-08-13',
    leadTimeDays: 4
  },
  {
    id: 'PRD-3023',
    sku: 'SKU-PKG-3023',
    name: 'Inflatable Air Pillow Cushioning Film Roll (1600ft)',
    category: 'Packaging',
    quantityAvailable: 14,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 60,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-06-04-C',
    supplier: 'EcoPack Global',
    unitPrice: 76.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'air',
    lastRestocked: '2026-07-27',
    leadTimeDays: 4
  },
  {
    id: 'PRD-3024',
    sku: 'SKU-PKG-3024',
    name: 'Moisture Barrier Static Shielding Bags 10x12',
    category: 'Packaging',
    quantityAvailable: 190,
    reservedQuantity: 30,
    damagedQuantity: 0,
    reorderLevel: 60,
    maxStock: 300,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-07-03-B',
    supplier: 'Silicon Dynamics',
    unitPrice: 45.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'shield_moon',
    lastRestocked: '2026-08-10',
    leadTimeDays: 3
  },
  {
    id: 'PRD-3025',
    sku: 'SKU-PKG-3025',
    name: 'Cardboard Box Resizer Scoring Tool Handheld',
    category: 'Packaging',
    quantityAvailable: 28,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 50,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-03-02-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 15.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'straighten',
    lastRestocked: '2026-08-04',
    leadTimeDays: 2
  },

  // ===================== ACCESSORIES (20 Products) =====================
  {
    id: 'PRD-4001',
    sku: 'SKU-ACC-4001',
    name: 'Dual-Monitor Full Motion Articulating Gas Spring Arm',
    category: 'Accessories',
    quantityAvailable: 58,
    reservedQuantity: 12,
    damagedQuantity: 1,
    reorderLevel: 25,
    maxStock: 100,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-02-01-A',
    supplier: 'ErgoForm Living',
    unitPrice: 85.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'monitor',
    lastRestocked: '2026-08-09',
    leadTimeDays: 4
  },
  {
    id: 'PRD-4002',
    sku: 'SKU-ACC-4002',
    name: 'USB-C 9-in-1 Multiport Hub with 100W PD',
    category: 'Accessories',
    quantityAvailable: 145,
    reservedQuantity: 30,
    damagedQuantity: 3,
    reorderLevel: 50,
    maxStock: 250,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-01-03-B',
    supplier: 'LogiPro Components',
    unitPrice: 48.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'usb',
    lastRestocked: '2026-08-12',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4003',
    sku: 'SKU-ACC-4003',
    name: 'Aluminum Foldable Laptop Stand Riser',
    category: 'Accessories',
    quantityAvailable: 9,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 150,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-03-02-A',
    supplier: 'ErgoForm Living',
    unitPrice: 29.50,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'laptop',
    lastRestocked: '2026-07-24',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4004',
    sku: 'SKU-ACC-4004',
    name: 'Memory Foam Keyboard & Mouse Wrist Rest Set',
    category: 'Accessories',
    quantityAvailable: 160,
    reservedQuantity: 25,
    damagedQuantity: 2,
    reorderLevel: 60,
    maxStock: 220,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-04-01-C',
    supplier: 'ComfortMat Pro',
    unitPrice: 22.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'front_hand',
    lastRestocked: '2026-08-11',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4005',
    sku: 'SKU-ACC-4005',
    name: '24" Privacy Screen Filter for Widescreen Monitors',
    category: 'Accessories',
    quantityAvailable: 42,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-02-04-B',
    supplier: 'ViewMaster Displays',
    unitPrice: 38.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'visibility_off',
    lastRestocked: '2026-08-06',
    leadTimeDays: 4
  },
  {
    id: 'PRD-4006',
    sku: 'SKU-ACC-4006',
    name: 'Under-Desk Swivel Headphone Hook Hanger',
    category: 'Accessories',
    quantityAvailable: 210,
    reservedQuantity: 20,
    damagedQuantity: 1,
    reorderLevel: 50,
    maxStock: 220,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-05-02-A',
    supplier: 'ErgoForm Living',
    unitPrice: 12.50,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'headphones',
    lastRestocked: '2026-08-13',
    leadTimeDays: 2
  },
  {
    id: 'PRD-4007',
    sku: 'SKU-ACC-4007',
    name: '12-Outlet Industrial Heavy Duty Surge Protector 15ft',
    category: 'Accessories',
    quantityAvailable: 34,
    reservedQuantity: 6,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 60,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-06-01-A',
    supplier: 'Netlink Infrastructure',
    unitPrice: 42.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'power',
    lastRestocked: '2026-08-05',
    leadTimeDays: 4
  },
  {
    id: 'PRD-4008',
    sku: 'SKU-ACC-4008',
    name: 'Screen Cleaning Spray Kit with Microfiber Cloths',
    category: 'Accessories',
    quantityAvailable: 175,
    reservedQuantity: 30,
    damagedQuantity: 2,
    reorderLevel: 50,
    maxStock: 250,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-07-02-C',
    supplier: 'Apex Office Essentials',
    unitPrice: 11.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'cleaning_services',
    lastRestocked: '2026-08-10',
    leadTimeDays: 2
  },
  {
    id: 'PRD-4009',
    sku: 'SKU-ACC-4009',
    name: 'Silicone Cable Clips Organizer 6-Channel (Pack of 6)',
    category: 'Accessories',
    quantityAvailable: 320,
    reservedQuantity: 40,
    damagedQuantity: 0,
    reorderLevel: 100,
    maxStock: 500,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-05-04-A',
    supplier: 'LogiPro Components',
    unitPrice: 8.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'cable',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },
  {
    id: 'PRD-4010',
    sku: 'SKU-ACC-4010',
    name: 'Wireless Bluetooth Presentation Clicker Remote',
    category: 'Accessories',
    quantityAvailable: 5,
    reservedQuantity: 6,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 60,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-03-03-B',
    supplier: 'LogiPro Components',
    unitPrice: 32.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'slideshow',
    lastRestocked: '2026-07-23',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4011',
    sku: 'SKU-ACC-4011',
    name: 'VESA Universal Adapter Mounting Plate Kit',
    category: 'Accessories',
    quantityAvailable: 68,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 120,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-02-03-D',
    supplier: 'ErgoForm Living',
    unitPrice: 19.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'tv',
    lastRestocked: '2026-08-07',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4012',
    sku: 'SKU-ACC-4012',
    name: 'Magnetic Cable Management Box (Large White)',
    category: 'Accessories',
    quantityAvailable: 45,
    reservedQuantity: 8,
    damagedQuantity: 1,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-06-03-A',
    supplier: 'ErgoForm Living',
    unitPrice: 24.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'inbox',
    lastRestocked: '2026-08-08',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4013',
    sku: 'SKU-ACC-4013',
    name: 'Active Stylus Digital Pen for Touchscreens',
    category: 'Accessories',
    quantityAvailable: 76,
    reservedQuantity: 12,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 110,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-01-04-C',
    supplier: 'Silicon Dynamics',
    unitPrice: 45.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'edit',
    lastRestocked: '2026-08-04',
    leadTimeDays: 4
  },
  {
    id: 'PRD-4014',
    sku: 'SKU-ACC-4014',
    name: 'Fast Qi Wireless Charging Mouse Pad 15W',
    category: 'Accessories',
    quantityAvailable: 18,
    reservedQuantity: 8,
    damagedQuantity: 1,
    reorderLevel: 25,
    maxStock: 70,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-04-03-A',
    supplier: 'LogiPro Components',
    unitPrice: 34.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'charging_station',
    lastRestocked: '2026-07-28',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4015',
    sku: 'SKU-ACC-4015',
    name: 'Heavy Duty Clamp-On Desk Power Strip (4 AC + 2 USB)',
    category: 'Accessories',
    quantityAvailable: 82,
    reservedQuantity: 14,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-06-02-C',
    supplier: 'Netlink Infrastructure',
    unitPrice: 39.90,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'power',
    lastRestocked: '2026-08-11',
    leadTimeDays: 4
  },
  {
    id: 'PRD-4016',
    sku: 'SKU-ACC-4016',
    name: 'Precision Screwdriver Toolset 64-in-1 Magnetic',
    category: 'Accessories',
    quantityAvailable: 115,
    reservedQuantity: 18,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 160,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-08-01-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 28.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'build',
    lastRestocked: '2026-08-09',
    leadTimeDays: 3
  },
  {
    id: 'PRD-4017',
    sku: 'SKU-ACC-4017',
    name: 'Adjustable Tablet / Smartphone Desktop Mount',
    category: 'Accessories',
    quantityAvailable: 140,
    reservedQuantity: 20,
    damagedQuantity: 0,
    reorderLevel: 50,
    maxStock: 150,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-03-01-D',
    supplier: 'ErgoForm Living',
    unitPrice: 18.50,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'stay_current_portrait',
    lastRestocked: '2026-08-14',
    leadTimeDays: 2
  },
  {
    id: 'PRD-4018',
    sku: 'SKU-ACC-4018',
    name: 'Anti-Glare Blue Light Screen Protector 27"',
    category: 'Accessories',
    quantityAvailable: 0,
    reservedQuantity: 0,
    damagedQuantity: 1,
    reorderLevel: 15,
    maxStock: 50,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-02-02-C',
    supplier: 'ViewMaster Displays',
    unitPrice: 32.00,
    aiPrediction: 'Dead Stock Risk',
    aiPredictionType: 'dead_stock',
    icon: 'filter_vintage',
    lastRestocked: '2026-06-25',
    leadTimeDays: 5
  },
  {
    id: 'PRD-4019',
    sku: 'SKU-ACC-4019',
    name: 'Webcam Privacy Cover Slider (Pack of 10)',
    category: 'Accessories',
    quantityAvailable: 480,
    reservedQuantity: 60,
    damagedQuantity: 0,
    reorderLevel: 150,
    maxStock: 800,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-01-01-A',
    supplier: 'LogiPro Components',
    unitPrice: 6.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'camera_alt',
    lastRestocked: '2026-08-10',
    leadTimeDays: 2
  },
  {
    id: 'PRD-4020',
    sku: 'SKU-ACC-4020',
    name: 'Braided Magnetic Breakaway USB-C Cable 10ft',
    category: 'Accessories',
    quantityAvailable: 230,
    reservedQuantity: 35,
    damagedQuantity: 2,
    reorderLevel: 70,
    maxStock: 350,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-07-04-B',
    supplier: 'LogiPro Components',
    unitPrice: 15.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'cable',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },

  // ===================== OFFICE SUPPLIES (20 Products) =====================
  {
    id: 'PRD-5001',
    sku: 'SKU-OFC-5001',
    name: 'Commercial Heavy Duty 200-Sheet Stapler',
    category: 'Office Supplies',
    quantityAvailable: 48,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 90,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-01-02-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 42.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'attach_file',
    lastRestocked: '2026-08-06',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5002',
    sku: 'SKU-OFC-5002',
    name: 'Industrial Permanent Markers Chisel Tip Black (Box of 36)',
    category: 'Office Supplies',
    quantityAvailable: 190,
    reservedQuantity: 40,
    damagedQuantity: 1,
    reorderLevel: 60,
    maxStock: 250,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-02-01-C',
    supplier: 'Apex Office Essentials',
    unitPrice: 28.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'draw',
    lastRestocked: '2026-08-11',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5003',
    sku: 'SKU-OFC-5003',
    name: 'Heavy Duty Storage Clipboards with Pen Holder (6pk)',
    category: 'Office Supplies',
    quantityAvailable: 85,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-03-03-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 34.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'assignment',
    lastRestocked: '2026-08-08',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5004',
    sku: 'SKU-OFC-5004',
    name: 'Self-Adhesive Notes Super Sticky 3x3 (24 Pads)',
    category: 'Office Supplies',
    quantityAvailable: 310,
    reservedQuantity: 45,
    damagedQuantity: 2,
    reorderLevel: 80,
    maxStock: 350,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-04-01-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 24.00,
    aiPrediction: 'Overstock Risk',
    aiPredictionType: 'overstock',
    icon: 'sticky_note_2',
    lastRestocked: '2026-08-13',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5005',
    sku: 'SKU-OFC-5005',
    name: 'Classification File Folders 2-Divider Box of 25',
    category: 'Office Supplies',
    quantityAvailable: 64,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 100,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-05-02-D',
    supplier: 'Apex Office Essentials',
    unitPrice: 48.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'folder',
    lastRestocked: '2026-08-05',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5006',
    sku: 'SKU-OFC-5006',
    name: 'Cross-Cut Paper Shredder Lubricant Sheets (Pack 24)',
    category: 'Office Supplies',
    quantityAvailable: 7,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 60,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-06-01-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 16.50,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'oil_barrel',
    lastRestocked: '2026-07-26',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5007',
    sku: 'SKU-OFC-5007',
    name: 'Magnetic Dry Erase Whiteboard Markers 12-Color',
    category: 'Office Supplies',
    quantityAvailable: 240,
    reservedQuantity: 35,
    damagedQuantity: 1,
    reorderLevel: 70,
    maxStock: 300,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-02-04-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 18.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'border_color',
    lastRestocked: '2026-08-10',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5008',
    sku: 'SKU-OFC-5008',
    name: 'All-Metal 3-Hole Adjustable Punch 40-Sheet',
    category: 'Office Supplies',
    quantityAvailable: 36,
    reservedQuantity: 6,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 70,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-01-04-C',
    supplier: 'Apex Office Essentials',
    unitPrice: 32.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'fiber_manual_record',
    lastRestocked: '2026-08-03',
    leadTimeDays: 4
  },
  {
    id: 'PRD-5009',
    sku: 'SKU-OFC-5009',
    name: 'Heavy Duty Retractable Badge Reels with Steel Cord (10pk)',
    category: 'Office Supplies',
    quantityAvailable: 185,
    reservedQuantity: 25,
    damagedQuantity: 0,
    reorderLevel: 50,
    maxStock: 250,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-07-02-A',
    supplier: 'SecureTech Systems',
    unitPrice: 21.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'badge',
    lastRestocked: '2026-08-09',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5010',
    sku: 'SKU-OFC-5010',
    name: 'Thermal Receipt Rolls 3-1/8" x 230ft BPA Free (50 Rolls)',
    category: 'Office Supplies',
    quantityAvailable: 110,
    reservedQuantity: 20,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 160,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-08-01-C',
    supplier: 'ZebraTech Supply',
    unitPrice: 58.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'receipt_long',
    lastRestocked: '2026-08-11',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5011',
    sku: 'SKU-OFC-5011',
    name: 'Premium 24lb Bright White Copy Paper 10 Reams (5000 Sheets)',
    category: 'Office Supplies',
    quantityAvailable: 75,
    reservedQuantity: 18,
    damagedQuantity: 2,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-09-01-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 62.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'layers',
    lastRestocked: '2026-08-07',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5012',
    sku: 'SKU-OFC-5012',
    name: 'Industrial Label Maker Tape Cartridges 1/2" White (5pk)',
    category: 'Office Supplies',
    quantityAvailable: 4,
    reservedQuantity: 5,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-06-03-A',
    supplier: 'ZebraTech Supply',
    unitPrice: 34.50,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'label_important',
    lastRestocked: '2026-07-25',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5013',
    sku: 'SKU-OFC-5013',
    name: 'Heavy Duty Scissors 8-Inch Titanium Coated (3pk)',
    category: 'Office Supplies',
    quantityAvailable: 95,
    reservedQuantity: 12,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 130,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-03-01-D',
    supplier: 'Apex Office Essentials',
    unitPrice: 19.99,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'content_cut',
    lastRestocked: '2026-08-08',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5014',
    sku: 'SKU-OFC-5014',
    name: 'Assorted Color Binder Clips (Tub of 140 Pieces)',
    category: 'Office Supplies',
    quantityAvailable: 155,
    reservedQuantity: 20,
    damagedQuantity: 0,
    reorderLevel: 50,
    maxStock: 200,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-04-04-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 14.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'folder_zip',
    lastRestocked: '2026-08-10',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5015',
    sku: 'SKU-OFC-5015',
    name: 'Dual-Power 12-Digit Desktop Financial Calculator',
    category: 'Office Supplies',
    quantityAvailable: 52,
    reservedQuantity: 8,
    damagedQuantity: 1,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-07-04-A',
    supplier: 'LogiPro Components',
    unitPrice: 22.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'calculate',
    lastRestocked: '2026-08-04',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5016',
    sku: 'SKU-OFC-5016',
    name: 'Expanding Accordion File Wallet 13-Pockets Letter Size',
    category: 'Office Supplies',
    quantityAvailable: 0,
    reservedQuantity: 0,
    damagedQuantity: 0,
    reorderLevel: 15,
    maxStock: 40,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-05-01-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 18.00,
    aiPrediction: 'Dead Stock Risk',
    aiPredictionType: 'dead_stock',
    icon: 'folder_open',
    lastRestocked: '2026-06-28',
    leadTimeDays: 4
  },
  {
    id: 'PRD-5017',
    sku: 'SKU-OFC-5017',
    name: 'Heavy Duty 2-Hole File Fasteners (Box of 100)',
    category: 'Office Supplies',
    quantityAvailable: 130,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 40,
    maxStock: 180,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-04-02-C',
    supplier: 'Apex Office Essentials',
    unitPrice: 12.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'pin',
    lastRestocked: '2026-08-09',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5018',
    sku: 'SKU-OFC-5018',
    name: 'A4 Laminating Pouches 5mil Glossy Thermal (100ct)',
    category: 'Office Supplies',
    quantityAvailable: 78,
    reservedQuantity: 14,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 110,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-08-04-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 26.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'picture_in_picture',
    lastRestocked: '2026-08-06',
    leadTimeDays: 3
  },
  {
    id: 'PRD-5019',
    sku: 'SKU-OFC-5019',
    name: 'Security Tinted Self-Seal #10 Business Envelopes (500ct)',
    category: 'Office Supplies',
    quantityAvailable: 115,
    reservedQuantity: 20,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 150,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-09-03-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 32.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'mail',
    lastRestocked: '2026-08-11',
    leadTimeDays: 2
  },
  {
    id: 'PRD-5020',
    sku: 'SKU-OFC-5020',
    name: 'Industrial Heavy Duty Packing Marker Broad Felt Tip Red (12pk)',
    category: 'Office Supplies',
    quantityAvailable: 165,
    reservedQuantity: 25,
    damagedQuantity: 0,
    reorderLevel: 45,
    maxStock: 180,
    warehouseZone: 'Mezzanine',
    shelfBinLocation: 'M-02-02-B',
    supplier: 'Apex Office Essentials',
    unitPrice: 19.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'brush',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },

  // ===================== EQUIPMENT & HARDWARE (20 Products) =====================
  {
    id: 'PRD-6001',
    sku: 'SKU-EQP-6001',
    name: 'Hydraulic Manual Pallet Jack 5500lb Capacity',
    category: 'Equipment',
    quantityAvailable: 6,
    reservedQuantity: 1,
    damagedQuantity: 0,
    reorderLevel: 5,
    maxStock: 10,
    warehouseZone: 'Dock Bay',
    shelfBinLocation: 'DOCK-BAY-01',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 420.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'front_loader',
    lastRestocked: '2026-07-28',
    leadTimeDays: 12
  },
  {
    id: 'PRD-6002',
    sku: 'SKU-EQP-6002',
    name: 'Digital Industrial Platform Scale 1000lb Capacity',
    category: 'Equipment',
    quantityAvailable: 14,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 8,
    maxStock: 20,
    warehouseZone: 'Dock Bay',
    shelfBinLocation: 'DOCK-BAY-03',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 380.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'scale',
    lastRestocked: '2026-08-02',
    leadTimeDays: 8
  },
  {
    id: 'PRD-6003',
    sku: 'SKU-EQP-6003',
    name: 'Convertible Aluminum Hand Truck Dolly 800lb',
    category: 'Equipment',
    quantityAvailable: 18,
    reservedQuantity: 4,
    damagedQuantity: 1,
    reorderLevel: 10,
    maxStock: 30,
    warehouseZone: 'Dock Bay',
    shelfBinLocation: 'DOCK-BAY-02',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 195.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'local_shipping',
    lastRestocked: '2026-08-04',
    leadTimeDays: 7
  },
  {
    id: 'PRD-6004',
    sku: 'SKU-EQP-6004',
    name: 'Auto-Retracting Safety Utility Box Cutters (Box 24)',
    category: 'Equipment',
    quantityAvailable: 120,
    reservedQuantity: 25,
    damagedQuantity: 2,
    reorderLevel: 40,
    maxStock: 180,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-01-01-A',
    supplier: 'Apex Office Essentials',
    unitPrice: 48.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'carpenter',
    lastRestocked: '2026-08-11',
    leadTimeDays: 3
  },
  {
    id: 'PRD-6005',
    sku: 'SKU-EQP-6005',
    name: 'Nitrile Coated Work Grip Gloves Size L (Pack of 12)',
    category: 'Equipment',
    quantityAvailable: 210,
    reservedQuantity: 30,
    damagedQuantity: 0,
    reorderLevel: 60,
    maxStock: 300,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-02-04-A',
    supplier: 'ComfortMat Pro',
    unitPrice: 26.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'front_hand',
    lastRestocked: '2026-08-13',
    leadTimeDays: 2
  },
  {
    id: 'PRD-6006',
    sku: 'SKU-EQP-6006',
    name: 'Anti-Fog ANSI Z87.1 Safety Eyewear Goggles (Box 12)',
    category: 'Equipment',
    quantityAvailable: 140,
    reservedQuantity: 20,
    damagedQuantity: 1,
    reorderLevel: 40,
    maxStock: 200,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-02-03-B',
    supplier: 'ComfortMat Pro',
    unitPrice: 38.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'visibility',
    lastRestocked: '2026-08-09',
    leadTimeDays: 3
  },
  {
    id: 'PRD-6007',
    sku: 'SKU-EQP-6007',
    name: 'Electric Pallet Truck Battery Replacement 24V',
    category: 'Equipment',
    quantityAvailable: 2,
    reservedQuantity: 1,
    damagedQuantity: 0,
    reorderLevel: 4,
    maxStock: 8,
    warehouseZone: 'Dock Bay',
    shelfBinLocation: 'DOCK-MAINT-01',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 780.00,
    aiPrediction: 'Restock in 3 Days',
    aiPredictionType: 'restock',
    icon: 'battery_alert',
    lastRestocked: '2026-07-15',
    leadTimeDays: 14
  },
  {
    id: 'PRD-6008',
    sku: 'SKU-EQP-6008',
    name: 'Laser Distance Measure Meter 165ft Range',
    category: 'Equipment',
    quantityAvailable: 25,
    reservedQuantity: 4,
    damagedQuantity: 0,
    reorderLevel: 10,
    maxStock: 40,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-09-04-A',
    supplier: 'ZebraTech Supply',
    unitPrice: 65.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'straighten',
    lastRestocked: '2026-08-05',
    leadTimeDays: 4
  },
  {
    id: 'PRD-6009',
    sku: 'SKU-HDW-7001',
    name: 'Heavy Duty Magnetic Warehouse Aisle Sign Holders (10pk)',
    category: 'Hardware',
    quantityAvailable: 95,
    reservedQuantity: 15,
    damagedQuantity: 0,
    reorderLevel: 30,
    maxStock: 120,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-12-01-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 44.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'signpost',
    lastRestocked: '2026-08-08',
    leadTimeDays: 3
  },
  {
    id: 'PRD-6010',
    sku: 'SKU-HDW-7002',
    name: 'Steel Racking Safety Wire Decking 48x42 (4pk)',
    category: 'Hardware',
    quantityAvailable: 40,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 60,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-22-01-A',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 135.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'grid_on',
    lastRestocked: '2026-08-02',
    leadTimeDays: 8
  },
  {
    id: 'PRD-6011',
    sku: 'SKU-HDW-7003',
    name: 'Floor Warning Cones "CAUTION WET FLOOR" 36" (6pk)',
    category: 'Hardware',
    quantityAvailable: 28,
    reservedQuantity: 4,
    damagedQuantity: 1,
    reorderLevel: 12,
    maxStock: 40,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-01-04-D',
    supplier: 'ComfortMat Pro',
    unitPrice: 58.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'warning',
    lastRestocked: '2026-08-03',
    leadTimeDays: 4
  },
  {
    id: 'PRD-6012',
    sku: 'SKU-HDW-7004',
    name: 'High-Visibility Orange Traffic Safety Vests (Pack of 20)',
    category: 'Hardware',
    quantityAvailable: 175,
    reservedQuantity: 20,
    damagedQuantity: 0,
    reorderLevel: 50,
    maxStock: 200,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-02-02-C',
    supplier: 'ComfortMat Pro',
    unitPrice: 32.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'sports_motorsports',
    lastRestocked: '2026-08-10',
    leadTimeDays: 2
  },
  {
    id: 'PRD-6013',
    sku: 'SKU-HDW-7005',
    name: 'Heavy Duty Brass Padlocks 50mm Keyed Alike (Pack of 6)',
    category: 'Hardware',
    quantityAvailable: 64,
    reservedQuantity: 10,
    damagedQuantity: 0,
    reorderLevel: 25,
    maxStock: 90,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-09-01-B',
    supplier: 'SecureTech Systems',
    unitPrice: 42.50,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'lock',
    lastRestocked: '2026-08-07',
    leadTimeDays: 3
  },
  {
    id: 'PRD-6014',
    sku: 'SKU-HDW-7006',
    name: 'Industrial Vinyl Aisle Marking Tape 3" x 36yd Yellow',
    category: 'Hardware',
    quantityAvailable: 48,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 60,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-12-03-A',
    supplier: 'ComfortMat Pro',
    unitPrice: 29.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'alt_route',
    lastRestocked: '2026-08-06',
    leadTimeDays: 3
  },
  {
    id: 'PRD-6015',
    sku: 'SKU-HDW-7007',
    name: 'Stackable Poly Warehouse Storage Totes 12-Gallon (6pk)',
    category: 'Hardware',
    quantityAvailable: 82,
    reservedQuantity: 12,
    damagedQuantity: 2,
    reorderLevel: 30,
    maxStock: 100,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-17-02-C',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 56.00,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'all_inbox',
    lastRestocked: '2026-08-11',
    leadTimeDays: 4
  },
  {
    id: 'PRD-6016',
    sku: 'SKU-HDW-7008',
    name: 'Industrial First Aid Eyewash Station Wall Mount 16oz',
    category: 'Hardware',
    quantityAvailable: 12,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 8,
    maxStock: 25,
    warehouseZone: 'Zone A',
    shelfBinLocation: 'A-02-01-A',
    supplier: 'ComfortMat Pro',
    unitPrice: 65.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'remove_red_eye',
    lastRestocked: '2026-07-29',
    leadTimeDays: 5
  },
  {
    id: 'PRD-6017',
    sku: 'SKU-HDW-7009',
    name: 'High Performance Industrial Cable Ties 14" (Pack of 500)',
    category: 'Hardware',
    quantityAvailable: 230,
    reservedQuantity: 30,
    damagedQuantity: 0,
    reorderLevel: 80,
    maxStock: 350,
    warehouseZone: 'Zone D',
    shelfBinLocation: 'D-08-03-A',
    supplier: 'LogiPro Components',
    unitPrice: 19.50,
    aiPrediction: 'Demand Increasing',
    aiPredictionType: 'increasing',
    icon: 'linear_scale',
    lastRestocked: '2026-08-12',
    leadTimeDays: 2
  },
  {
    id: 'PRD-6018',
    sku: 'SKU-HDW-7010',
    name: 'Heavy Duty 4-Wheel Platform Truck Flatbed Cart 1200lb',
    category: 'Equipment',
    quantityAvailable: 7,
    reservedQuantity: 2,
    damagedQuantity: 0,
    reorderLevel: 6,
    maxStock: 15,
    warehouseZone: 'Dock Bay',
    shelfBinLocation: 'DOCK-BAY-04',
    supplier: 'IronGrip Logistics Gear',
    unitPrice: 290.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'pallet',
    lastRestocked: '2026-08-01',
    leadTimeDays: 9
  },
  {
    id: 'PRD-6019',
    sku: 'SKU-HDW-7011',
    name: 'Warehouse Barcode Scanner Stand Flexible Arm Gooseneck',
    category: 'Equipment',
    quantityAvailable: 55,
    reservedQuantity: 8,
    damagedQuantity: 0,
    reorderLevel: 20,
    maxStock: 80,
    warehouseZone: 'Zone B',
    shelfBinLocation: 'B-01-02-B',
    supplier: 'ZebraTech Supply',
    unitPrice: 28.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'sensors',
    lastRestocked: '2026-08-08',
    leadTimeDays: 3
  },
  {
    id: 'PRD-6020',
    sku: 'SKU-HDW-7012',
    name: 'Corrugated Waste Recycling Bin 40-Gallon (Set of 3)',
    category: 'Hardware',
    quantityAvailable: 42,
    reservedQuantity: 6,
    damagedQuantity: 1,
    reorderLevel: 15,
    maxStock: 60,
    warehouseZone: 'Zone C',
    shelfBinLocation: 'C-12-04-A',
    supplier: 'EcoPack Global',
    unitPrice: 36.00,
    aiPrediction: 'Stable Demand',
    aiPredictionType: 'stable',
    icon: 'delete',
    lastRestocked: '2026-08-05',
    leadTimeDays: 3
  }
];

export const initialFullInventory: InventoryItem[] = rawProductsList.map((raw) => {
  const status = calculateStockStatus(raw.quantityAvailable, raw.reorderLevel, raw.maxStock);
  const stockPercentage = computeStockPercentage(raw.quantityAvailable, raw.maxStock);

  return {
    ...raw,
    status,
    stockPercentage,
    // compatibility
    currentStock: raw.quantityAvailable,
    muthuPredict: raw.aiPrediction,
    muthuPredictType:
      raw.aiPredictionType === 'depletion'
        ? 'depletion'
        : raw.aiPredictionType === 'restock'
        ? 'restock'
        : raw.aiPredictionType === 'overstock' || raw.aiPredictionType === 'dead_stock'
        ? 'low_velocity'
        : 'stable',
    locationZone: `${raw.warehouseZone} • ${raw.shelfBinLocation}`,
    unitCost: raw.unitPrice
  };
});
