import { TruckShipment, LogisticsStats, MuthuLogisticsRecommendation } from './types';

export const INITIAL_TRUCKS: TruckShipment[] = [
  // 1. Ready to Depart (12 Trucks)
  {
    id: 'TRK-01',
    truckId: 'TRK-HYD-01',
    driverName: 'Ramesh Naidu',
    driverContact: '+91 98480 23412',
    vehicleNumber: 'AP 05 XX 1234',
    vehicleType: '24ft Heavy Freight Container',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 88,
    currentLoadKg: 8360,
    origin: 'Hyderabad Central Hub (Bay-04)',
    destination: 'Vijayawada Distribution Terminal',
    route: 'NH65 Vijayawada Expressway',
    departureTime: '11:45 AM',
    eta: '04:30 PM (Today)',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 14,
    orderIds: ['ORD-MTH-1042', 'ORD-89104', 'ORD-89108'],
    distanceKm: 275,
    delayRisk: 'None',
    currentLocationDesc: 'Staging Bay 04 • Gate Pass Cleared',
    fuelLevelPercent: 95,
    progressPercent: 0,
    lastUpdated: '5 mins ago',
    muthuRecommendation: {
      problem: 'High priority cold-chain cartons staged at bay rear.',
      reason: 'Ambient temperature rising on NH65 corridor (+34°C).',
      impact: 'Risk of shelf-life degradation if departure delayed past 12:00 PM.',
      recommendation: 'Authorize immediate gate pass and lock thermal logger.',
      confidence: 98,
      action: 'Authorize Immediate Gate Pass'
    }
  },
  {
    id: 'TRK-02',
    truckId: 'TRK-HYD-02',
    driverName: 'Suresh Kumar',
    driverContact: '+91 98491 55678',
    vehicleNumber: 'TS 09 XX 5678',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 92,
    currentLoadKg: 3864,
    origin: 'Hyderabad Central Hub (Bay-02)',
    destination: 'Guntur Logistics Park',
    route: 'NH65 & Guntur Bypass',
    departureTime: '12:15 PM',
    eta: '05:00 PM',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 9,
    orderIds: ['ORD-89112', 'ORD-89115'],
    distanceKm: 285,
    delayRisk: 'None',
    currentLocationDesc: 'Staging Bay 02 • Final Document Audit',
    fuelLevelPercent: 90,
    progressPercent: 0,
    lastUpdated: '8 mins ago'
  },
  {
    id: 'TRK-03',
    truckId: 'TRK-HYD-03',
    driverName: 'Venkatesh Rao',
    driverContact: '+91 99890 33441',
    vehicleNumber: 'KA 01 XX 4321',
    vehicleType: '32ft Multi-Axle Trailer',
    capacityPallets: 26,
    capacityKg: 16000,
    currentLoadPercent: 94,
    currentLoadKg: 15040,
    origin: 'Hyderabad Central Hub (Bay-08)',
    destination: 'Bengaluru South Cross-Dock (Electronic City)',
    route: 'NH44 Hyderabad-Bengaluru Corridor',
    departureTime: '12:30 PM',
    eta: '10:30 PM',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 28,
    orderIds: ['ORD-89120', 'ORD-89122'],
    distanceKm: 570,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 08 • E-Way Bill Synchronized',
    fuelLevelPercent: 98,
    progressPercent: 0,
    lastUpdated: '12 mins ago'
  },
  {
    id: 'TRK-04',
    truckId: 'TRK-HYD-04',
    driverName: 'Rajesh Goud',
    driverContact: '+91 94401 88990',
    vehicleNumber: 'TN 10 XX 8765',
    vehicleType: '20ft Container Truck',
    capacityPallets: 14,
    capacityKg: 7500,
    currentLoadPercent: 86,
    currentLoadKg: 6450,
    origin: 'Hyderabad Central Hub (Bay-06)',
    destination: 'Chennai Industrial Zone (Sriperumbudur)',
    route: 'NH16 Coastal Express Corridor',
    departureTime: '01:00 PM',
    eta: '02:00 AM (Tomorrow)',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 16,
    orderIds: ['ORD-89125'],
    distanceKm: 630,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 06 • Seal #MTH-9021 Applied',
    fuelLevelPercent: 92,
    progressPercent: 0,
    lastUpdated: '15 mins ago'
  },
  {
    id: 'TRK-05',
    truckId: 'TRK-HYD-05',
    driverName: 'Manpreet Singh',
    driverContact: '+91 98112 44321',
    vehicleNumber: 'MH 12 XX 9988',
    vehicleType: '24ft Freight Liner',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 85,
    currentLoadKg: 8075,
    origin: 'Hyderabad Central Hub (Bay-05)',
    destination: 'Pune Tech Hub (Chakan)',
    route: 'NH65 Pune Highway',
    departureTime: '01:15 PM',
    eta: '11:00 PM',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 22,
    orderIds: ['ORD-89130'],
    distanceKm: 560,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 05 • Weighbridge Cleared (8.07T)',
    fuelLevelPercent: 96,
    progressPercent: 0,
    lastUpdated: '20 mins ago'
  },
  {
    id: 'TRK-06',
    truckId: 'TRK-HYD-06',
    driverName: 'Karthik Narayanan',
    driverContact: '+91 97900 11223',
    vehicleNumber: 'AP 16 XX 3456',
    vehicleType: 'Tata Ace E-Cargo Van',
    capacityPallets: 4,
    capacityKg: 1800,
    currentLoadPercent: 98,
    currentLoadKg: 1764,
    origin: 'Hyderabad Central Hub (Bay-01)',
    destination: 'Rajahmundry FMCG Depot',
    route: 'NH16 Arterial Corridor',
    departureTime: '01:30 PM',
    eta: '08:30 PM',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2C Express Courier',
    orderCount: 42,
    orderIds: ['ORD-89135'],
    distanceKm: 425,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 01 • Courier Scan Handover Done',
    fuelLevelPercent: 100,
    progressPercent: 0,
    lastUpdated: '22 mins ago'
  },
  {
    id: 'TRK-07',
    truckId: 'TRK-HYD-07',
    driverName: 'Anand Swamy',
    driverContact: '+91 98860 77889',
    vehicleNumber: 'TS 07 XX 6789',
    vehicleType: '14ft High-Deck Truck',
    capacityPallets: 10,
    capacityKg: 5000,
    currentLoadPercent: 91,
    currentLoadKg: 4550,
    origin: 'Hyderabad Central Hub (Bay-03)',
    destination: 'Kakinada Deepwater Logistics',
    route: 'NH16 & Port Link',
    departureTime: '01:45 PM',
    eta: '09:45 PM',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 11,
    orderIds: ['ORD-89140'],
    distanceKm: 490,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 03 • Pre-Departure Checklist Complete',
    fuelLevelPercent: 88,
    progressPercent: 0,
    lastUpdated: '25 mins ago'
  },
  {
    id: 'TRK-08',
    truckId: 'TRK-HYD-08',
    driverName: 'Pradeep Verma',
    driverContact: '+91 99100 88776',
    vehicleNumber: 'DL 01 XX 2233',
    vehicleType: '32ft Container Super-Express',
    capacityPallets: 28,
    capacityKg: 18000,
    currentLoadPercent: 96,
    currentLoadKg: 17280,
    origin: 'Hyderabad Central Hub (Bay-09)',
    destination: 'Delhi NCR Fulfillment Center (Bilaspur)',
    route: 'NH44 North-South Super Corridor',
    departureTime: '02:00 PM',
    eta: '06:00 AM (2 Days)',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 38,
    orderIds: ['ORD-89145'],
    distanceKm: 1540,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 09 • GPS & Speed-Governor Calibrated',
    fuelLevelPercent: 100,
    progressPercent: 0,
    lastUpdated: '30 mins ago'
  },
  {
    id: 'TRK-09',
    truckId: 'TRK-HYD-09',
    driverName: 'Mohammed Imran',
    driverContact: '+91 93910 44556',
    vehicleNumber: 'AP 26 XX 8901',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 89,
    currentLoadKg: 3738,
    origin: 'Hyderabad Central Hub (Bay-07)',
    destination: 'Nellore Logistics Hub',
    route: 'NH16 South Coastal Expressway',
    departureTime: '02:15 PM',
    eta: '09:00 PM',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 15,
    orderIds: ['ORD-89150'],
    distanceKm: 450,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 07 • Driver Briefing Conducted',
    fuelLevelPercent: 94,
    progressPercent: 0,
    lastUpdated: '35 mins ago'
  },
  {
    id: 'TRK-10',
    truckId: 'TRK-HYD-10',
    driverName: 'Sandeep Reddy',
    driverContact: '+91 98481 99001',
    vehicleNumber: 'OD 02 XX 7766',
    vehicleType: '24ft Refrigerated Container',
    capacityPallets: 16,
    capacityKg: 8500,
    currentLoadPercent: 93,
    currentLoadKg: 7905,
    origin: 'Hyderabad Central Hub (Cold Bay C1)',
    destination: 'Bhubaneswar Pharma Depot',
    route: 'NH16 Eastern Arterial Corridor',
    departureTime: '02:30 PM',
    eta: '07:30 AM (Tomorrow)',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 19,
    orderIds: ['ORD-89155'],
    distanceKm: 1050,
    delayRisk: 'None',
    temperatureDegC: 4.2,
    currentLocationDesc: 'Cold Bay C1 • Temp Stable at 4.2°C',
    fuelLevelPercent: 98,
    progressPercent: 0,
    lastUpdated: '40 mins ago'
  },
  {
    id: 'TRK-11',
    truckId: 'TRK-HYD-11',
    driverName: 'Vikram Patel',
    driverContact: '+91 98250 33221',
    vehicleNumber: 'WB 04 XX 1122',
    vehicleType: '28ft Freight Truck',
    capacityPallets: 22,
    capacityKg: 12000,
    currentLoadPercent: 87,
    currentLoadKg: 10440,
    origin: 'Hyderabad Central Hub (Bay-10)',
    destination: 'Kolkata Central Hub (Dankuni)',
    route: 'NH16 & Asian Highway 45',
    departureTime: '02:45 PM',
    eta: '02:00 PM (2 Days)',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 31,
    orderIds: ['ORD-89160'],
    distanceKm: 1480,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 10 • Manifest Invoiced',
    fuelLevelPercent: 95,
    progressPercent: 0,
    lastUpdated: '45 mins ago'
  },
  {
    id: 'TRK-12',
    truckId: 'TRK-HYD-12',
    driverName: 'Sunil Sharma',
    driverContact: '+91 97170 66554',
    vehicleNumber: 'TS 08 XX 4567',
    vehicleType: '20ft Heavy Container',
    capacityPallets: 14,
    capacityKg: 7500,
    currentLoadPercent: 95,
    currentLoadKg: 7125,
    origin: 'Hyderabad Central Hub (Bay-11)',
    destination: 'Mumbai Western Central (Bhiwandi)',
    route: 'NH65 & Expressway Link',
    departureTime: '03:00 PM',
    eta: '06:00 AM (Tomorrow)',
    currentStatus: 'Ready to Depart',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 24,
    orderIds: ['ORD-89165'],
    distanceKm: 710,
    delayRisk: 'None',
    currentLocationDesc: 'Bay 11 • Loading Ramp Cleared',
    fuelLevelPercent: 91,
    progressPercent: 0,
    lastUpdated: '50 mins ago'
  },

  // 2. Trucks Being Loaded (5 Trucks)
  {
    id: 'TRK-13',
    truckId: 'TRK-HYD-13',
    driverName: 'Balaji Naidu',
    driverContact: '+91 98488 12345',
    vehicleNumber: 'AP 04 XX 9876',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 62,
    currentLoadKg: 2604,
    origin: 'Hyderabad Central Hub (Dock 12)',
    destination: 'Visakhapatnam Port Logistics Park',
    route: 'NH16 Coastal Highway',
    departureTime: '03:30 PM (Est.)',
    eta: '02:00 AM (Tomorrow)',
    currentStatus: 'Loading',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 12,
    orderIds: ['ORD-89170'],
    distanceKm: 620,
    delayRisk: 'Low',
    currentLocationDesc: 'Loading Dock 12 • 5/8 Pallets Loaded',
    fuelLevelPercent: 85,
    progressPercent: 0,
    lastUpdated: '4 mins ago',
    muthuRecommendation: {
      problem: 'Forklift 3 battery low during dock loading.',
      reason: 'Operator switched to manual pallet jack slowing rate.',
      impact: 'May push departure by 15 mins.',
      recommendation: 'Assign Forklift 1 from Bay 02 to complete final 3 pallets.',
      confidence: 96,
      action: 'Reassign Forklift 1'
    }
  },
  {
    id: 'TRK-14',
    truckId: 'TRK-HYD-14',
    driverName: 'Naveen Reddy',
    driverContact: '+91 99490 22334',
    vehicleNumber: 'TS 10 XX 7890',
    vehicleType: 'Eicher Pro 3019 Heavy',
    capacityPallets: 16,
    capacityKg: 9000,
    currentLoadPercent: 45,
    currentLoadKg: 4050,
    origin: 'Hyderabad Central Hub (Dock 14)',
    destination: 'Chennai Central Distribution',
    route: 'NH16 Highway Link',
    departureTime: '04:00 PM (Est.)',
    eta: '05:00 AM (Tomorrow)',
    currentStatus: 'Loading',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 18,
    orderIds: ['ORD-89175'],
    distanceKm: 630,
    delayRisk: 'None',
    currentLocationDesc: 'Loading Dock 14 • 7/16 Pallets Staged',
    fuelLevelPercent: 90,
    progressPercent: 0,
    lastUpdated: '10 mins ago'
  },
  {
    id: 'TRK-15',
    truckId: 'TRK-HYD-15',
    driverName: 'Raghavan Pillai',
    driverContact: '+91 94470 55667',
    vehicleNumber: 'KA 05 XX 3344',
    vehicleType: '24ft Freight Container',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 78,
    currentLoadKg: 7410,
    origin: 'Hyderabad Central Hub (Dock 15)',
    destination: 'Bengaluru Industrial Area (Peenya)',
    route: 'NH44 Expressway',
    departureTime: '04:15 PM (Est.)',
    eta: '02:30 AM (Tomorrow)',
    currentStatus: 'Loading',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 25,
    orderIds: ['ORD-89180'],
    distanceKm: 575,
    delayRisk: 'None',
    currentLocationDesc: 'Loading Dock 15 • 14/18 Pallets Positioned',
    fuelLevelPercent: 92,
    progressPercent: 0,
    lastUpdated: '14 mins ago'
  },
  {
    id: 'TRK-16',
    truckId: 'TRK-HYD-16',
    driverName: 'Sanjay Deshmukh',
    driverContact: '+91 98220 88991',
    vehicleNumber: 'MH 14 XX 6543',
    vehicleType: '14ft High-Deck Vehicle',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 50,
    currentLoadKg: 2100,
    origin: 'Hyderabad Central Hub (Dock 16)',
    destination: 'Pune Distribution Depot',
    route: 'NH65 Pune Highway',
    departureTime: '04:30 PM (Est.)',
    eta: '03:00 AM (Tomorrow)',
    currentStatus: 'Loading',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 14,
    orderIds: ['ORD-89185'],
    distanceKm: 560,
    delayRisk: 'None',
    currentLocationDesc: 'Loading Dock 16 • Pallet Shrink-Wrapping',
    fuelLevelPercent: 88,
    progressPercent: 0,
    lastUpdated: '18 mins ago'
  },
  {
    id: 'TRK-17',
    truckId: 'TRK-HYD-17',
    driverName: 'Gopal Krishna',
    driverContact: '+91 98485 77665',
    vehicleNumber: 'AP 31 XX 1122',
    vehicleType: 'Tata 407 Parcel Carrier',
    capacityPallets: 6,
    capacityKg: 3000,
    currentLoadPercent: 35,
    currentLoadKg: 1050,
    origin: 'Hyderabad Central Hub (Dock 17)',
    destination: 'Vijayawada Express Parcel Hub',
    route: 'NH65 Expressway',
    departureTime: '05:00 PM (Est.)',
    eta: '10:00 PM',
    currentStatus: 'Loading',
    shipmentType: 'B2C Express Courier',
    orderCount: 58,
    orderIds: ['ORD-89190'],
    distanceKm: 275,
    delayRisk: 'None',
    currentLocationDesc: 'Loading Dock 17 • Barcode Batch Ingestion',
    fuelLevelPercent: 95,
    progressPercent: 0,
    lastUpdated: '20 mins ago'
  },

  // 3. Delayed Trucks (2 Trucks)
  {
    id: 'TRK-18',
    truckId: 'TRK-HYD-18',
    driverName: 'Ashok Varma',
    driverContact: '+91 98482 66778',
    vehicleNumber: 'AP 05 XX 9988',
    vehicleType: '24ft Freight Truck',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 92,
    currentLoadKg: 8740,
    origin: 'Hyderabad Central Hub',
    destination: 'Vijayawada Distribution Terminal',
    route: 'NH65 Vijayawada Corridor (Keesara Toll Plaza)',
    departureTime: '08:00 AM',
    eta: '02:15 PM (Delayed by 32m)',
    currentStatus: 'Delayed',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 18,
    orderIds: ['ORD-89195'],
    distanceKm: 275,
    delayRisk: 'High',
    delayMinutes: 32,
    delayReason: 'Heavy toll congestion and lane maintenance near Keesara Toll Plaza.',
    currentLocationDesc: 'KM 142 • Keesara Toll Plaza Bypass',
    fuelLevelPercent: 68,
    progressPercent: 52,
    lastUpdated: '2 mins ago',
    muthuRecommendation: {
      problem: 'Muthu predicts a 32-minute delay on the Vijayawada route.',
      reason: 'NH65 Lane 2 closed for bridge surfacing at KM 142.',
      impact: '3 priority hospital pharma deliveries at risk of missing 02:00 PM SLA.',
      recommendation: 'Reroute driver via Nandigama State Link Road (Save 24 mins). Driver notified.',
      confidence: 97,
      action: 'Dispatch Nandigama Reroute Instructions'
    }
  },
  {
    id: 'TRK-19',
    truckId: 'TRK-HYD-19',
    driverName: 'Gurdeep Dhillon',
    driverContact: '+91 98765 11223',
    vehicleNumber: 'TS 09 XX 3344',
    vehicleType: '28ft Multi-Axle Freight',
    capacityPallets: 22,
    capacityKg: 12000,
    currentLoadPercent: 95,
    currentLoadKg: 11400,
    origin: 'Hyderabad Central Hub',
    destination: 'Visakhapatnam Port Logistics',
    route: 'NH16 Coastal Express (Annavaram Section)',
    departureTime: '06:30 AM',
    eta: '04:45 PM (Delayed by 45m)',
    currentStatus: 'Delayed',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 24,
    orderIds: ['ORD-89200'],
    distanceKm: 620,
    delayRisk: 'High',
    delayMinutes: 45,
    delayReason: 'Tyre pressure warning light resolved; slow heavy transport queue at Rajahmundry toll.',
    currentLocationDesc: 'KM 380 • Near Annavaram Ghat Approach',
    fuelLevelPercent: 62,
    progressPercent: 61,
    lastUpdated: '6 mins ago',
    muthuRecommendation: {
      problem: 'Truck 19 running 45 minutes behind schedule.',
      reason: 'Scheduled stop at Annavaram weigh station took 28 minutes longer than estimated.',
      impact: 'Visakhapatnam container vessel cutoff at 06:00 PM tight.',
      recommendation: 'Pre-clear port terminal green channel pass with Visakhapatnam Port Authority.',
      confidence: 94,
      action: 'Trigger Green Channel Port Token'
    }
  },

  // 4. Trucks Currently En Route (18 Trucks)
  {
    id: 'TRK-20',
    truckId: 'TRK-HYD-20',
    driverName: 'Prakash Rao',
    driverContact: '+91 98480 99881',
    vehicleNumber: 'AP 09 XX 4567',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 88,
    currentLoadKg: 3696,
    origin: 'Hyderabad Central Hub',
    destination: 'Kakinada Deepwater Hub',
    route: 'NH16 Coastal Corridor',
    departureTime: '07:00 AM',
    eta: '03:15 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 12,
    orderIds: ['ORD-89205'],
    distanceKm: 490,
    delayRisk: 'None',
    currentLocationDesc: 'KM 310 • Passing Eluru Bypass',
    fuelLevelPercent: 74,
    progressPercent: 63,
    lastUpdated: '5 mins ago'
  },
  {
    id: 'TRK-21',
    truckId: 'TRK-HYD-21',
    driverName: 'Sitaram Murthy',
    driverContact: '+91 98492 11223',
    vehicleNumber: 'TS 07 XX 8899',
    vehicleType: '24ft Freight Truck',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 91,
    currentLoadKg: 8645,
    origin: 'Hyderabad Central Hub',
    destination: 'Bengaluru South Cross-Dock',
    route: 'NH44 Hyderabad-Bengaluru Corridor',
    departureTime: '06:00 AM',
    eta: '04:00 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 26,
    orderIds: ['ORD-89210'],
    distanceKm: 570,
    delayRisk: 'None',
    currentLocationDesc: 'KM 380 • Anantapur Bypass',
    fuelLevelPercent: 65,
    progressPercent: 67,
    lastUpdated: '7 mins ago'
  },
  {
    id: 'TRK-22',
    truckId: 'TRK-HYD-22',
    driverName: 'Mani Ratnam',
    driverContact: '+91 97910 44332',
    vehicleNumber: 'TN 02 XX 7788',
    vehicleType: '20ft Container Truck',
    capacityPallets: 14,
    capacityKg: 7500,
    currentLoadPercent: 86,
    currentLoadKg: 6450,
    origin: 'Hyderabad Central Hub',
    destination: 'Chennai Sriperumbudur Hub',
    route: 'NH16 Coastal Express',
    departureTime: '05:30 AM',
    eta: '04:30 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 18,
    orderIds: ['ORD-89215'],
    distanceKm: 630,
    delayRisk: 'None',
    currentLocationDesc: 'KM 440 • Ongole Highway Stretch',
    fuelLevelPercent: 58,
    progressPercent: 70,
    lastUpdated: '10 mins ago'
  },
  {
    id: 'TRK-23',
    truckId: 'TRK-HYD-23',
    driverName: 'Sanjay Kadam',
    driverContact: '+91 98230 77665',
    vehicleNumber: 'MH 12 XX 5544',
    vehicleType: '24ft Freight Liner',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 94,
    currentLoadKg: 8930,
    origin: 'Hyderabad Central Hub',
    destination: 'Pune Tech Zone',
    route: 'NH65 Pune Highway',
    departureTime: '06:15 AM',
    eta: '03:45 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 22,
    orderIds: ['ORD-89220'],
    distanceKm: 560,
    delayRisk: 'None',
    currentLocationDesc: 'KM 365 • Solapur Expressway Section',
    fuelLevelPercent: 62,
    progressPercent: 65,
    lastUpdated: '12 mins ago'
  },
  {
    id: 'TRK-24',
    truckId: 'TRK-HYD-24',
    driverName: 'Devendra Joshi',
    driverContact: '+91 99200 44556',
    vehicleNumber: 'MH 04 XX 2233',
    vehicleType: '28ft Container',
    capacityPallets: 22,
    capacityKg: 12000,
    currentLoadPercent: 96,
    currentLoadKg: 11520,
    origin: 'Hyderabad Central Hub',
    destination: 'Mumbai Bhiwandi Logistics Hub',
    route: 'NH65 & Expressway',
    departureTime: '04:00 AM',
    eta: '05:30 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 30,
    orderIds: ['ORD-89225'],
    distanceKm: 710,
    delayRisk: 'None',
    currentLocationDesc: 'KM 520 • Pune-Mumbai Expressway Approach',
    fuelLevelPercent: 52,
    progressPercent: 73,
    lastUpdated: '15 mins ago'
  },
  {
    id: 'TRK-25',
    truckId: 'TRK-HYD-25',
    driverName: 'Arun Kumar',
    driverContact: '+91 98483 11223',
    vehicleNumber: 'TS 09 XX 1199',
    vehicleType: 'Tata Ace E-Cargo Van',
    capacityPallets: 4,
    capacityKg: 1800,
    currentLoadPercent: 100,
    currentLoadKg: 1800,
    origin: 'Hyderabad Central Hub',
    destination: 'Guntur Consumer Depot',
    route: 'NH65 Corridor',
    departureTime: '08:30 AM',
    eta: '01:30 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2C Express Courier',
    orderCount: 52,
    orderIds: ['ORD-89230'],
    distanceKm: 285,
    delayRisk: 'None',
    currentLocationDesc: 'KM 210 • Miryalaguda Bypass',
    fuelLevelPercent: 78,
    progressPercent: 74,
    lastUpdated: '18 mins ago'
  },
  {
    id: 'TRK-26',
    truckId: 'TRK-HYD-26',
    driverName: 'Krishna Murthy',
    driverContact: '+91 98480 66554',
    vehicleNumber: 'AP 05 XX 7788',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 88,
    currentLoadKg: 3696,
    origin: 'Hyderabad Central Hub',
    destination: 'Rajahmundry FMCG Depot',
    route: 'NH16 Corridor',
    departureTime: '07:30 AM',
    eta: '02:45 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 14,
    orderIds: ['ORD-89235'],
    distanceKm: 425,
    delayRisk: 'None',
    currentLocationDesc: 'KM 290 • Vijayawada Outer Ring Road',
    fuelLevelPercent: 70,
    progressPercent: 68,
    lastUpdated: '20 mins ago'
  },
  {
    id: 'TRK-27',
    truckId: 'TRK-HYD-27',
    driverName: 'Harpreet Singh',
    driverContact: '+91 98140 22331',
    vehicleNumber: 'DL 01 XX 7788',
    vehicleType: '32ft Multi-Axle Freight',
    capacityPallets: 28,
    capacityKg: 18000,
    currentLoadPercent: 97,
    currentLoadKg: 17460,
    origin: 'Hyderabad Central Hub',
    destination: 'Delhi NCR Bilaspur Hub',
    route: 'NH44 Super Corridor',
    departureTime: 'Yesterday 10:00 PM',
    eta: 'Tomorrow 08:00 AM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 42,
    orderIds: ['ORD-89240'],
    distanceKm: 1540,
    delayRisk: 'None',
    currentLocationDesc: 'KM 860 • Near Gwalior Section',
    fuelLevelPercent: 64,
    progressPercent: 56,
    lastUpdated: '25 mins ago'
  },
  {
    id: 'TRK-28',
    truckId: 'TRK-HYD-28',
    driverName: 'Jagannath Mohanty',
    driverContact: '+91 94370 11223',
    vehicleNumber: 'OD 02 XX 3344',
    vehicleType: '24ft Freight Truck',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 90,
    currentLoadKg: 8550,
    origin: 'Hyderabad Central Hub',
    destination: 'Bhubaneswar Logistics Depot',
    route: 'NH16 Corridor',
    departureTime: 'Yesterday 08:00 PM',
    eta: 'Today 04:00 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 20,
    orderIds: ['ORD-89245'],
    distanceKm: 1050,
    delayRisk: 'None',
    currentLocationDesc: 'KM 820 • Berhampur Link Stretch',
    fuelLevelPercent: 55,
    progressPercent: 78,
    lastUpdated: '30 mins ago'
  },
  {
    id: 'TRK-29',
    truckId: 'TRK-HYD-29',
    driverName: 'Deepak Ghosh',
    driverContact: '+91 98300 44556',
    vehicleNumber: 'WB 04 XX 5566',
    vehicleType: '28ft Heavy Container',
    capacityPallets: 22,
    capacityKg: 12000,
    currentLoadPercent: 93,
    currentLoadKg: 11160,
    origin: 'Hyderabad Central Hub',
    destination: 'Kolkata Dankuni Hub',
    route: 'NH16 Corridor',
    departureTime: 'Yesterday 06:00 PM',
    eta: 'Tomorrow 06:00 AM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 34,
    orderIds: ['ORD-89250'],
    distanceKm: 1480,
    delayRisk: 'None',
    currentLocationDesc: 'KM 980 • Balasore Highway Section',
    fuelLevelPercent: 60,
    progressPercent: 66,
    lastUpdated: '35 mins ago'
  },
  {
    id: 'TRK-30',
    truckId: 'TRK-HYD-30',
    driverName: 'Vijay Naidu',
    driverContact: '+91 98484 22331',
    vehicleNumber: 'AP 26 XX 3344',
    vehicleType: '14ft High-Deck Truck',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 88,
    currentLoadKg: 3696,
    origin: 'Hyderabad Central Hub',
    destination: 'Nellore Logistics Hub',
    route: 'NH16 Corridor',
    departureTime: '08:00 AM',
    eta: '03:30 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 16,
    orderIds: ['ORD-89255'],
    distanceKm: 450,
    delayRisk: 'None',
    currentLocationDesc: 'KM 260 • Chilakaluripet Bypass',
    fuelLevelPercent: 72,
    progressPercent: 58,
    lastUpdated: '40 mins ago'
  },
  {
    id: 'TRK-31',
    truckId: 'TRK-HYD-31',
    driverName: 'Chiranjeevi Rao',
    driverContact: '+91 98495 66778',
    vehicleNumber: 'TS 09 XX 9900',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 86,
    currentLoadKg: 3612,
    origin: 'Hyderabad Central Hub',
    destination: 'Vijayawada Distribution Terminal',
    route: 'NH65 Corridor',
    departureTime: '09:00 AM',
    eta: '02:00 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 15,
    orderIds: ['ORD-89260'],
    distanceKm: 275,
    delayRisk: 'None',
    currentLocationDesc: 'KM 180 • Suryapet Highway Stretch',
    fuelLevelPercent: 80,
    progressPercent: 65,
    lastUpdated: '42 mins ago'
  },
  {
    id: 'TRK-32',
    truckId: 'TRK-HYD-32',
    driverName: 'Sanjay Gupta',
    driverContact: '+91 98105 88990',
    vehicleNumber: 'DL 01 XX 5566',
    vehicleType: '24ft Freight Container',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 92,
    currentLoadKg: 8740,
    origin: 'Hyderabad Central Hub',
    destination: 'Bengaluru South Cross-Dock',
    route: 'NH44 Corridor',
    departureTime: '07:15 AM',
    eta: '05:15 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 22,
    orderIds: ['ORD-89265'],
    distanceKm: 570,
    delayRisk: 'None',
    currentLocationDesc: 'KM 290 • Kurnool Toll Link',
    fuelLevelPercent: 68,
    progressPercent: 51,
    lastUpdated: '45 mins ago'
  },
  {
    id: 'TRK-33',
    truckId: 'TRK-HYD-33',
    driverName: 'Ravindran Nair',
    driverContact: '+91 94471 22334',
    vehicleNumber: 'TN 10 XX 4455',
    vehicleType: '20ft Container Truck',
    capacityPallets: 14,
    capacityKg: 7500,
    currentLoadPercent: 89,
    currentLoadKg: 6675,
    origin: 'Hyderabad Central Hub',
    destination: 'Chennai Central Depot',
    route: 'NH16 Corridor',
    departureTime: '06:45 AM',
    eta: '05:30 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 17,
    orderIds: ['ORD-89270'],
    distanceKm: 630,
    delayRisk: 'None',
    currentLocationDesc: 'KM 360 • Nellore Outer Bypass',
    fuelLevelPercent: 64,
    progressPercent: 57,
    lastUpdated: '50 mins ago'
  },
  {
    id: 'TRK-34',
    truckId: 'TRK-HYD-34',
    driverName: 'Mahesh Shinde',
    driverContact: '+91 98221 44556',
    vehicleNumber: 'MH 12 XX 1199',
    vehicleType: '14ft High-Deck Truck',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 91,
    currentLoadKg: 3822,
    origin: 'Hyderabad Central Hub',
    destination: 'Pune Tech Zone',
    route: 'NH65 Corridor',
    departureTime: '07:45 AM',
    eta: '04:45 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 16,
    orderIds: ['ORD-89275'],
    distanceKm: 560,
    delayRisk: 'None',
    currentLocationDesc: 'KM 280 • Humnabad Section',
    fuelLevelPercent: 72,
    progressPercent: 50,
    lastUpdated: '52 mins ago'
  },
  {
    id: 'TRK-35',
    truckId: 'TRK-HYD-35',
    driverName: 'Satyanarayana Raju',
    driverContact: '+91 98481 33445',
    vehicleNumber: 'AP 05 XX 6655',
    vehicleType: '24ft Freight Truck',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 90,
    currentLoadKg: 8550,
    origin: 'Hyderabad Central Hub',
    destination: 'Visakhapatnam Port Logistics',
    route: 'NH16 Corridor',
    departureTime: '06:00 AM',
    eta: '04:00 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 21,
    orderIds: ['ORD-89280'],
    distanceKm: 620,
    delayRisk: 'None',
    currentLocationDesc: 'KM 390 • Tuni Coastal Highway',
    fuelLevelPercent: 66,
    progressPercent: 63,
    lastUpdated: '55 mins ago'
  },
  {
    id: 'TRK-36',
    truckId: 'TRK-HYD-36',
    driverName: 'Ajay Varma',
    driverContact: '+91 98485 11229',
    vehicleNumber: 'TS 09 XX 2233',
    vehicleType: 'Tata 407 Parcel Carrier',
    capacityPallets: 6,
    capacityKg: 3000,
    currentLoadPercent: 95,
    currentLoadKg: 2850,
    origin: 'Hyderabad Central Hub',
    destination: 'Vijayawada Express Parcel Hub',
    route: 'NH65 Corridor',
    departureTime: '09:15 AM',
    eta: '02:15 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2C Express Courier',
    orderCount: 64,
    orderIds: ['ORD-89285'],
    distanceKm: 275,
    delayRisk: 'None',
    currentLocationDesc: 'KM 195 • Kodad Toll Approach',
    fuelLevelPercent: 82,
    progressPercent: 71,
    lastUpdated: '58 mins ago'
  },
  {
    id: 'TRK-37',
    truckId: 'TRK-HYD-37',
    driverName: 'Srinivas Naidu',
    driverContact: '+91 98488 44556',
    vehicleNumber: 'AP 04 XX 5566',
    vehicleType: '20ft Container Truck',
    capacityPallets: 14,
    capacityKg: 7500,
    currentLoadPercent: 93,
    currentLoadKg: 6975,
    origin: 'Hyderabad Central Hub',
    destination: 'Kakinada Deepwater Hub',
    route: 'NH16 Corridor',
    departureTime: '07:15 AM',
    eta: '03:45 PM',
    currentStatus: 'En Route',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 18,
    orderIds: ['ORD-89290'],
    distanceKm: 490,
    delayRisk: 'None',
    currentLocationDesc: 'KM 330 • Tadepalligudem Bypass',
    fuelLevelPercent: 68,
    progressPercent: 67,
    lastUpdated: '1 hour ago'
  },

  // 5. Returning Trucks (4 Trucks)
  {
    id: 'TRK-38',
    truckId: 'TRK-HYD-38',
    driverName: 'Girish Reddy',
    driverContact: '+91 98499 11223',
    vehicleNumber: 'AP 05 XX 8899',
    vehicleType: '14ft Closed Container',
    capacityPallets: 8,
    capacityKg: 4200,
    currentLoadPercent: 0,
    currentLoadKg: 0,
    origin: 'Vijayawada Distribution Terminal',
    destination: 'Hyderabad Central Hub (Inbound)',
    route: 'NH65 Westbound Expressway',
    departureTime: '09:30 AM',
    eta: '02:15 PM (Today)',
    currentStatus: 'Returning',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 0,
    orderIds: [],
    distanceKm: 275,
    delayRisk: 'None',
    currentLocationDesc: 'KM 190 • Westbound Suryapet Link',
    fuelLevelPercent: 72,
    progressPercent: 69,
    lastUpdated: '10 mins ago',
    muthuRecommendation: {
      problem: 'Truck 38 returning empty from Vijayawada (100% deadhead).',
      reason: 'Standard scheduled return trip.',
      impact: '₹4,800 unoptimized fuel cost on empty return run.',
      recommendation: 'Auto-allocate 6 return pallets of packaging materials from Vijayawada supplier.',
      confidence: 96,
      action: 'Assign Vijayawada Inbound Backhaul'
    }
  },
  {
    id: 'TRK-39',
    truckId: 'TRK-HYD-39',
    driverName: 'Venkata Ramana',
    driverContact: '+91 98482 44556',
    vehicleNumber: 'TS 09 XX 4433',
    vehicleType: '24ft Freight Truck',
    capacityPallets: 18,
    capacityKg: 9500,
    currentLoadPercent: 12,
    currentLoadKg: 1140,
    origin: 'Guntur Logistics Park',
    destination: 'Hyderabad Central Hub (Inbound)',
    route: 'NH65 Westbound',
    departureTime: '08:45 AM',
    eta: '01:45 PM',
    currentStatus: 'Returning',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 2,
    orderIds: [],
    distanceKm: 285,
    delayRisk: 'None',
    currentLocationDesc: 'KM 220 • Narketpally Bypass',
    fuelLevelPercent: 65,
    progressPercent: 77,
    lastUpdated: '15 mins ago'
  },
  {
    id: 'TRK-40',
    truckId: 'TRK-HYD-40',
    driverName: 'Manohar Rao',
    driverContact: '+91 98483 77889',
    vehicleNumber: 'KA 01 XX 8899',
    vehicleType: '32ft Trailer',
    capacityPallets: 26,
    capacityKg: 16000,
    currentLoadPercent: 0,
    currentLoadKg: 0,
    origin: 'Bengaluru South Cross-Dock',
    destination: 'Hyderabad Central Hub (Inbound)',
    route: 'NH44 Northbound',
    departureTime: '04:00 AM',
    eta: '02:00 PM',
    currentStatus: 'Returning',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 0,
    orderIds: [],
    distanceKm: 570,
    delayRisk: 'None',
    currentLocationDesc: 'KM 470 • Jadcherla Toll Approach',
    fuelLevelPercent: 55,
    progressPercent: 82,
    lastUpdated: '20 mins ago'
  },
  {
    id: 'TRK-41',
    truckId: 'TRK-HYD-41',
    driverName: 'Prashant Patil',
    driverContact: '+91 98222 33445',
    vehicleNumber: 'MH 12 XX 7766',
    vehicleType: '20ft Container Truck',
    capacityPallets: 14,
    capacityKg: 7500,
    currentLoadPercent: 0,
    currentLoadKg: 0,
    origin: 'Pune Tech Zone',
    destination: 'Hyderabad Central Hub (Inbound)',
    route: 'NH65 Eastbound',
    departureTime: '05:00 AM',
    eta: '03:00 PM',
    currentStatus: 'Returning',
    shipmentType: 'B2B Wholesale Freight',
    orderCount: 0,
    orderIds: [],
    distanceKm: 560,
    delayRisk: 'None',
    currentLocationDesc: 'KM 430 • Zaheerabad Highway Stretch',
    fuelLevelPercent: 58,
    progressPercent: 76,
    lastUpdated: '25 mins ago'
  },

  // 6. Delivered Trucks (Representative items matching count 31)
  ...Array.from({ length: 31 }, (_, index) => {
    const num = index + 42;
    const cities = ['Vijayawada', 'Guntur', 'Visakhapatnam', 'Chennai', 'Bengaluru', 'Pune', 'Nellore', 'Kakinada', 'Rajahmundry', 'Bhubaneswar'];
    const destCity = cities[index % cities.length];
    const drivers = ['Ravi Teja', 'Narayana Swamy', 'Kiran Kumar', 'Satish Reddy', 'Dhanush Verma', 'Sudheer Babu', 'Bhanu Prakash', 'Goutham Naidu', 'Siddharth Rao', 'Praveen Goud'];
    const driver = drivers[index % drivers.length];
    const plates = ['AP 05 XX ', 'TS 09 XX ', 'KA 01 XX ', 'TN 10 XX ', 'MH 12 XX '];
    const plate = `${plates[index % plates.length]}${1000 + num * 37}`;

    return {
      id: `TRK-${num}`,
      truckId: `TRK-HYD-${num}`,
      driverName: driver,
      driverContact: `+91 9848${index} ${10000 + num * 11}`,
      vehicleNumber: plate,
      vehicleType: index % 3 === 0 ? '24ft Freight Container' : index % 3 === 1 ? '14ft Closed Container' : 'Tata Ace E-Cargo',
      capacityPallets: 14,
      capacityKg: 7500,
      currentLoadPercent: 0,
      currentLoadKg: 0,
      origin: 'Hyderabad Central Hub',
      destination: `${destCity} Terminal Hub`,
      route: `Direct Arterial NH Route to ${destCity}`,
      departureTime: '05:00 AM (Delivered)',
      eta: 'Completed (On-Time)',
      currentStatus: 'Delivered' as const,
      shipmentType: index % 2 === 0 ? 'B2B Wholesale Freight' as const : 'B2C Express Courier' as const,
      orderCount: 15 + (index % 10),
      orderIds: [`ORD-DEL-${num}`],
      distanceKm: 250 + (index * 25),
      delayRisk: 'None' as const,
      currentLocationDesc: `Delivered at ${destCity} Receiving Dock • POD Verified`,
      fuelLevelPercent: 85,
      progressPercent: 100,
      lastUpdated: 'Delivered Today'
    };
  })
];

export const INITIAL_LOGISTICS_STATS: LogisticsStats = {
  readyToDepartCount: 12,
  loadingCount: 5,
  enRouteCount: 18,
  returningCount: 4,
  deliveredCount: 31,
  delayedCount: 2,
  availableCapacityTons: 142.5,
  todayDispatchesCount: 48,
  activeFleetCount: 72,
  onTimeDeliveryRate: 98.4
};

export const MUTHU_LOGISTICS_DECISION_INSIGHTS: MuthuLogisticsRecommendation[] = [
  {
    problem: 'Truck AP 05 XX 1234 is 88% loaded and ready to depart for Vijayawada.',
    reason: '14 wholesale hospital equipment orders fully staged and audited at Staging Bay 04.',
    impact: 'Dispatching now guarantees arrival 45 minutes ahead of hospital receiving dock cutoff.',
    recommendation: 'Authorize immediate dispatch for Truck AP 05 XX 1234 before midday toll buildup.',
    confidence: 99,
    action: 'Authorize Gate Clearance'
  },
  {
    problem: 'Muthu predicts a 32-minute delay on the Vijayawada NH65 route near Keesara.',
    reason: 'NH65 Lane 2 closed for bridge resurfacing with heavy toll queues at KM 142.',
    impact: 'Truck AP 05 XX 9988 carrying 18 urgent orders will miss express SLA window.',
    recommendation: 'Reroute driver via Nandigama State Link Road (Save 24 mins). Send GPS update.',
    confidence: 97,
    action: 'Transmit GPS Reroute'
  },
  {
    problem: 'Truck 08 (DL 01 XX 2233) has 3 urgent medical cold-chain orders assigned.',
    reason: 'Scheduled departure is 02:00 PM, but temperature sensor shows ambient surge (+36°C).',
    impact: 'Risk of cold-chain SLA breach if held at staging bay past 01:30 PM.',
    recommendation: 'Advance Truck 08 dispatch sequence ahead of standard freight lanes.',
    confidence: 98,
    action: 'Prioritize Truck 08 Dispatch'
  },
  {
    problem: 'Muthu detected unused capacity of 18% on Truck TRK-HYD-14 (Dock 14).',
    reason: 'Chennai route pallet cluster has 3 additional staged pallets ready in Bulk Zone C.',
    impact: 'Adding the 3 pallets increases truck utilization to 96% and saves ₹8,200 in separate freight.',
    recommendation: 'Consolidate 3 staged pallets from Lane C-04 onto Truck 14 before seal.',
    confidence: 95,
    action: 'Consolidate 3 Pallets'
  }
];
