import { Worker } from './types';

export const INITIAL_WORKERS: Worker[] = [
  // 1. Ravi Kumar (Packer - Top Performer)
  {
    id: 'wrk-101',
    workerId: 'EMP-401',
    name: 'Ravi Kumar',
    role: 'Packer',
    shift: 'Morning',
    zone: 'Zone B (Electronics)',
    availability: 'On Shift',
    ordersHandled: 42,
    packagesPicked: 0,
    packagesPacked: 186,
    qcChecks: 14,
    avgProcessingTimeMinutes: 4.2,
    productivityScore: 96,
    attendancePercent: 98,
    currentWorkloadPercent: 88,
    slaContributionPercent: 98,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 480000,
    recommendedBonusInr: 5000,
    bonusReason: 'Top 5% productivity score (96/100) + 98% SLA compliance rate across 186 packed orders.',
    bonusApproved: false,
    recognitionCategory: 'Top Performer',
    recognitionReason: 'Operates 18% above shift packing speed average with zero packaging transit damage reports.',
    performanceNote: 'Consistently operates 18% above team packing velocity average.'
  },
  // 2. Asha Reddy (Picker - Needs Training)
  {
    id: 'wrk-102',
    workerId: 'EMP-402',
    name: 'Asha Reddy',
    role: 'Picker',
    shift: 'Morning',
    zone: 'Zone A (Furniture)',
    availability: 'On Shift',
    ordersHandled: 38,
    packagesPicked: 210,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 6.1,
    productivityScore: 84,
    attendancePercent: 94,
    currentWorkloadPercent: 78,
    slaContributionPercent: 91,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 390000,
    recognitionCategory: 'Needs Training',
    recognitionReason: 'Picking accuracy is 91% compared to team benchmark of 96%. High speed picker who needs barcode scan verification refresher.',
    trainingRecommended: 'Picking accuracy refresher training (Accuracy: 91% vs 96% team avg)',
    performanceNote: 'High speed picker, accuracy can improve with barcode scan verification.'
  },
  // 3. Vikram Singh (Quality Inspector - Top Performer)
  {
    id: 'wrk-103',
    workerId: 'EMP-403',
    name: 'Vikram Singh',
    role: 'Quality Inspector',
    shift: 'Morning',
    zone: 'Zone B (Electronics)',
    availability: 'On Shift',
    ordersHandled: 64,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 194,
    avgProcessingTimeMinutes: 3.5,
    productivityScore: 98,
    attendancePercent: 100,
    currentWorkloadPercent: 92,
    slaContributionPercent: 99,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 620000,
    recommendedBonusInr: 6500,
    bonusReason: 'Zero customer defect returns across 194 inspected high-value enterprise medical shipments.',
    bonusApproved: false,
    recognitionCategory: 'Top Performer',
    recognitionReason: 'Identified 12 defective lithium battery batches before pallet sealing, avoiding potential major customer returns.',
    performanceNote: 'Identified 12 defective battery batches before pallet sealing.'
  },
  // 4. Priya Sharma (Dispatcher - High Impact)
  {
    id: 'wrk-104',
    workerId: 'EMP-404',
    name: 'Priya Sharma',
    role: 'Dispatcher',
    shift: 'Morning',
    zone: 'Dock Bay',
    availability: 'On Shift',
    ordersHandled: 55,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 55,
    avgProcessingTimeMinutes: 5.0,
    productivityScore: 92,
    attendancePercent: 96,
    currentWorkloadPercent: 82,
    slaContributionPercent: 96,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 540000,
    recognitionCategory: 'High Impact',
    recognitionReason: 'Streamlined dock bay gate pass handoffs, cutting truck turnaround time by 12 minutes.',
    performanceNote: 'Manages outbound truck gate pass verifications at Dock 4 & 5.'
  },
  // 5. Suresh Babu (Loader - On Track)
  {
    id: 'wrk-105',
    workerId: 'EMP-405',
    name: 'Suresh Babu',
    role: 'Loader',
    shift: 'Afternoon',
    zone: 'Dock Bay',
    availability: 'Available',
    ordersHandled: 49,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 7.2,
    productivityScore: 89,
    attendancePercent: 92,
    currentWorkloadPercent: 65,
    slaContributionPercent: 93,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 410000,
    performanceNote: 'Heavy pallet loader assigned to Vijayawada expressway trucks.'
  },
  // 6. Ananya Patel (Packer - Overloaded / Needs Improvement)
  {
    id: 'wrk-106',
    workerId: 'EMP-406',
    name: 'Ananya Patel',
    role: 'Packer',
    shift: 'Afternoon',
    zone: 'Zone C (Packaging)',
    availability: 'Overloaded',
    ordersHandled: 51,
    packagesPicked: 0,
    packagesPacked: 220,
    qcChecks: 0,
    avgProcessingTimeMinutes: 5.8,
    productivityScore: 78,
    attendancePercent: 88,
    currentWorkloadPercent: 135,
    slaContributionPercent: 84,
    performanceStatus: 'NEEDS IMPROVEMENT',
    estimatedRevenueSupportedInr: 320000,
    recognitionCategory: 'Performance Review',
    recognitionReason: 'Packing queue bottleneck at Station 2 caused SLA drop. Workload at 135% warrants immediate second packer allocation.',
    trainingRecommended: 'Ergonomic packing workflow and box-sizing optimization coaching.',
    performanceNote: 'Overloaded due to Packing Station 2 backlog. Needs support worker.'
  },
  // 7. Rajesh Varma (Driver - High Impact)
  {
    id: 'wrk-107',
    workerId: 'EMP-407',
    name: 'Rajesh Varma',
    role: 'Driver',
    shift: 'Morning',
    zone: 'Logistics Corridor',
    availability: 'On Shift',
    ordersHandled: 18,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 45.0,
    productivityScore: 94,
    attendancePercent: 96,
    currentWorkloadPercent: 85,
    slaContributionPercent: 95,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 850000,
    recognitionCategory: 'High Impact',
    recognitionReason: '100% on-time delivery across NH65 arterial highway runs with zero transit discrepancies.',
    performanceNote: 'Senior driver operating AP 05 XX 1234 on NH65 Vijayawada corridor.'
  },
  // 8. Meena Iyer (Supervisor - Top Performer)
  {
    id: 'wrk-108',
    workerId: 'EMP-408',
    name: 'Meena Iyer',
    role: 'Supervisor',
    shift: 'Morning',
    zone: 'Mezzanine',
    availability: 'On Shift',
    ordersHandled: 120,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 120,
    avgProcessingTimeMinutes: 2.0,
    productivityScore: 99,
    attendancePercent: 100,
    currentWorkloadPercent: 90,
    slaContributionPercent: 99,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 1200000,
    recommendedBonusInr: 8000,
    bonusReason: 'Zero SLA breaches across Shift 1 floor management across 480 orders.',
    bonusApproved: false,
    recognitionCategory: 'Top Performer',
    recognitionReason: 'Flawless floor coordination between picking lines, QC station, and outbound docks.',
    performanceNote: 'Floor supervisor directing Zone A and B packaging lines.'
  },
  // 9. Kiran Naik (Maintenance Technician - On Track)
  {
    id: 'wrk-109',
    workerId: 'EMP-409',
    name: 'Kiran Naik',
    role: 'Maintenance Technician',
    shift: 'Morning',
    zone: 'Zone D (Accessories)',
    availability: 'On Shift',
    ordersHandled: 15,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 15,
    avgProcessingTimeMinutes: 20.0,
    productivityScore: 91,
    attendancePercent: 95,
    currentWorkloadPercent: 75,
    slaContributionPercent: 94,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 450000,
    performanceNote: 'Assigned to Forklift FL-07 and Conveyor Belt CV-02 preventive servicing.'
  },
  // 10. Deepak Chawla (Picker - Good)
  {
    id: 'wrk-110',
    workerId: 'EMP-410',
    name: 'Deepak Chawla',
    role: 'Picker',
    shift: 'Afternoon',
    zone: 'Zone B (Electronics)',
    availability: 'Available',
    ordersHandled: 34,
    packagesPicked: 175,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 5.5,
    productivityScore: 86,
    attendancePercent: 92,
    currentWorkloadPercent: 70,
    slaContributionPercent: 90,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 340000,
    performanceNote: 'Fast runner for small electronics totes.'
  },
  // 11. Sunita Rao (Warehouse Associate - Most Improved)
  {
    id: 'wrk-111',
    workerId: 'EMP-411',
    name: 'Sunita Rao',
    role: 'Warehouse Associate',
    shift: 'Night',
    zone: 'Zone C (Packaging)',
    availability: 'On Break',
    ordersHandled: 28,
    packagesPicked: 90,
    packagesPacked: 80,
    qcChecks: 10,
    avgProcessingTimeMinutes: 6.0,
    productivityScore: 82,
    attendancePercent: 90,
    currentWorkloadPercent: 60,
    slaContributionPercent: 88,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 280000,
    recognitionCategory: 'Most Improved',
    recognitionReason: 'Cross-trained across picking, packing, and bin staging with 15% productivity gain this month.',
    performanceNote: 'Multi-skilled night shift associate supporting inventory consolidation.'
  },
  // 12. Arjun Das (Packer - Excellent)
  {
    id: 'wrk-112',
    workerId: 'EMP-412',
    name: 'Arjun Das',
    role: 'Packer',
    shift: 'Morning',
    zone: 'Zone A (Furniture)',
    availability: 'On Shift',
    ordersHandled: 39,
    packagesPicked: 0,
    packagesPacked: 160,
    qcChecks: 0,
    avgProcessingTimeMinutes: 4.8,
    productivityScore: 93,
    attendancePercent: 97,
    currentWorkloadPercent: 82,
    slaContributionPercent: 95,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 450000,
    performanceNote: 'Expert heavy furniture box assembly packer.'
  },
  // 13. Lakshmi Narayana (Picker - Top Performer)
  {
    id: 'wrk-113',
    workerId: 'EMP-113',
    name: 'Lakshmi Narayana',
    role: 'Picker',
    shift: 'Morning',
    zone: 'Mezzanine',
    availability: 'On Shift',
    ordersHandled: 44,
    packagesPicked: 240,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 4.0,
    productivityScore: 97,
    attendancePercent: 99,
    currentWorkloadPercent: 85,
    slaContributionPercent: 97,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 520000,
    recommendedBonusInr: 4500,
    bonusReason: 'Highest mezzanine picking volume with 99.2% scan accuracy across Q1.',
    bonusApproved: false,
    recognitionCategory: 'Top Performer',
    recognitionReason: 'Maintains fastest pick speed in vertical mezzanine racks with near-perfect pick accuracy.',
    performanceNote: 'Mezzanine bin picking specialist.'
  },
  // 14. Ganesh Pillai (Driver - Good)
  {
    id: 'wrk-114',
    workerId: 'EMP-114',
    name: 'Ganesh Pillai',
    role: 'Driver',
    shift: 'Afternoon',
    zone: 'Logistics Corridor',
    availability: 'On Shift',
    ordersHandled: 14,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 50.0,
    productivityScore: 90,
    attendancePercent: 94,
    currentWorkloadPercent: 80,
    slaContributionPercent: 92,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 710000,
    performanceNote: 'Operating TS 09 XX 5678 to Hyderabad Cyberabad.'
  },
  // 15. Kavita Sengupta (Quality Inspector - Excellent)
  {
    id: 'wrk-115',
    workerId: 'EMP-115',
    name: 'Kavita Sengupta',
    role: 'Quality Inspector',
    shift: 'Afternoon',
    zone: 'Zone A (Furniture)',
    availability: 'On Shift',
    ordersHandled: 48,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 145,
    avgProcessingTimeMinutes: 4.1,
    productivityScore: 95,
    attendancePercent: 96,
    currentWorkloadPercent: 85,
    slaContributionPercent: 96,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 490000,
    performanceNote: 'Performs wooden furniture seal checks and transit wrap audits.'
  },
  // 16. Manoj Joshi (Loader - On Leave)
  {
    id: 'wrk-116',
    workerId: 'EMP-116',
    name: 'Manoj Joshi',
    role: 'Loader',
    shift: 'Night',
    zone: 'Dock Bay',
    availability: 'On Leave',
    ordersHandled: 0,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 0.0,
    productivityScore: 85,
    attendancePercent: 91,
    currentWorkloadPercent: 0,
    slaContributionPercent: 89,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 150000,
    performanceNote: 'Scheduled leave approved by HR.'
  },
  // 17. Karthik Swaminathan (Supervisor - High Impact)
  {
    id: 'wrk-117',
    workerId: 'EMP-117',
    name: 'Karthik Swaminathan',
    role: 'Supervisor',
    shift: 'Afternoon',
    zone: 'Dock Bay',
    availability: 'On Shift',
    ordersHandled: 95,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 95,
    avgProcessingTimeMinutes: 2.5,
    productivityScore: 96,
    attendancePercent: 98,
    currentWorkloadPercent: 85,
    slaContributionPercent: 97,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 980000,
    recommendedBonusInr: 5000,
    bonusReason: 'Managed afternoon dock surge with zero delayed truck dispatches.',
    bonusApproved: false,
    recognitionCategory: 'High Impact',
    recognitionReason: 'Coordinated loading bay traffic and minimized courier wait times by 18%.',
    performanceNote: 'Senior outbound logistics supervisor.'
  },
  // 18. Divya Menon (Picker - Good)
  {
    id: 'wrk-118',
    workerId: 'EMP-118',
    name: 'Divya Menon',
    role: 'Picker',
    shift: 'Morning',
    zone: 'Zone D (Accessories)',
    availability: 'On Shift',
    ordersHandled: 36,
    packagesPicked: 190,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 4.9,
    productivityScore: 88,
    attendancePercent: 95,
    currentWorkloadPercent: 75,
    slaContributionPercent: 92,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 360000,
    performanceNote: 'Small parts and barcode accessories bin picker.'
  },
  // 19. Sandeep Mukherjee (Maintenance Technician - Excellent)
  {
    id: 'wrk-119',
    workerId: 'EMP-119',
    name: 'Sandeep Mukherjee',
    role: 'Maintenance Technician',
    shift: 'Afternoon',
    zone: 'Mezzanine',
    availability: 'On Shift',
    ordersHandled: 18,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 18,
    avgProcessingTimeMinutes: 18.0,
    productivityScore: 93,
    attendancePercent: 97,
    currentWorkloadPercent: 72,
    slaContributionPercent: 95,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 490000,
    recognitionCategory: 'Most Improved',
    recognitionReason: 'Reduced conveyor breakdown downtime by 24% through proactive sensor replacements.',
    performanceNote: 'Mezzanine sortation and automated crane technician.'
  },
  // 20. Sneha Kulkarni (Packer - Good)
  {
    id: 'wrk-120',
    workerId: 'EMP-120',
    name: 'Sneha Kulkarni',
    role: 'Packer',
    shift: 'Night',
    zone: 'Zone B (Electronics)',
    availability: 'On Shift',
    ordersHandled: 35,
    packagesPicked: 0,
    packagesPacked: 155,
    qcChecks: 0,
    avgProcessingTimeMinutes: 4.5,
    productivityScore: 90,
    attendancePercent: 96,
    currentWorkloadPercent: 78,
    slaContributionPercent: 93,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 410000,
    performanceNote: 'Night shift high-value electronics packer.'
  },
  // 21. Harish Venkat (Loader - Under Review)
  {
    id: 'wrk-121',
    workerId: 'EMP-121',
    name: 'Harish Venkat',
    role: 'Loader',
    shift: 'Morning',
    zone: 'Dock Bay',
    availability: 'On Shift',
    ordersHandled: 26,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 11.5,
    productivityScore: 68,
    attendancePercent: 82,
    currentWorkloadPercent: 55,
    slaContributionPercent: 74,
    performanceStatus: 'UNDER REVIEW',
    estimatedRevenueSupportedInr: 210000,
    recognitionCategory: 'Performance Review',
    recognitionReason: 'Attendance dropped to 82% with average loading time 45% above shift target. Supervisor audit scheduled.',
    trainingRecommended: 'Hydraulic pallet jack handling & dock safety refresher.',
    performanceNote: 'Performance Review Required: Loading velocity lagging; assigned mentor for 2 weeks.'
  },
  // 22. Pooja Nair (Dispatcher - Good)
  {
    id: 'wrk-122',
    workerId: 'EMP-122',
    name: 'Pooja Nair',
    role: 'Dispatcher',
    shift: 'Afternoon',
    zone: 'Dock Bay',
    availability: 'On Shift',
    ordersHandled: 44,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 44,
    avgProcessingTimeMinutes: 5.2,
    productivityScore: 89,
    attendancePercent: 94,
    currentWorkloadPercent: 76,
    slaContributionPercent: 91,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 470000,
    performanceNote: 'Inbound return manifest processor and courier dispatch handoff.'
  },
  // 23. Nithin George (Driver - Excellent)
  {
    id: 'wrk-123',
    workerId: 'EMP-123',
    name: 'Nithin George',
    role: 'Driver',
    shift: 'Night',
    zone: 'Logistics Corridor',
    availability: 'On Shift',
    ordersHandled: 16,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 48.0,
    productivityScore: 95,
    attendancePercent: 98,
    currentWorkloadPercent: 82,
    slaContributionPercent: 96,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 780000,
    performanceNote: 'Interstate overnight hauler operating KA 01 XX 7890 to Bangalore Hub.'
  },
  // 24. Radhika Deshmukh (Warehouse Associate - On Track)
  {
    id: 'wrk-124',
    workerId: 'EMP-124',
    name: 'Radhika Deshmukh',
    role: 'Warehouse Associate',
    shift: 'Morning',
    zone: 'Zone A (Furniture)',
    availability: 'On Shift',
    ordersHandled: 32,
    packagesPicked: 110,
    packagesPacked: 60,
    qcChecks: 25,
    avgProcessingTimeMinutes: 5.4,
    productivityScore: 87,
    attendancePercent: 93,
    currentWorkloadPercent: 74,
    slaContributionPercent: 91,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 340000,
    performanceNote: 'Supports pallet staging and stock replenishment in Zone A.'
  },
  // 25. Balaji Sundaram (Picker - Good)
  {
    id: 'wrk-125',
    workerId: 'EMP-125',
    name: 'Balaji Sundaram',
    role: 'Picker',
    shift: 'Afternoon',
    zone: 'Zone C (Packaging)',
    availability: 'On Shift',
    ordersHandled: 35,
    packagesPicked: 180,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 5.1,
    productivityScore: 88,
    attendancePercent: 94,
    currentWorkloadPercent: 76,
    slaContributionPercent: 92,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 350000,
    performanceNote: 'Corrugated cartons and packaging material pick runner.'
  },
  // 26. Farhan Qureshi (Loader - Good)
  {
    id: 'wrk-126',
    workerId: 'EMP-126',
    name: 'Farhan Qureshi',
    role: 'Loader',
    shift: 'Afternoon',
    zone: 'Dock Bay',
    availability: 'Available',
    ordersHandled: 42,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 6.8,
    productivityScore: 89,
    attendancePercent: 95,
    currentWorkloadPercent: 68,
    slaContributionPercent: 93,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 380000,
    performanceNote: 'Forklift assistant and pallet strapping loader.'
  },
  // 27. Madhuri Bhosale (Packer - Most Improved)
  {
    id: 'wrk-127',
    workerId: 'EMP-127',
    name: 'Madhuri Bhosale',
    role: 'Packer',
    shift: 'Morning',
    zone: 'Zone D (Accessories)',
    availability: 'On Shift',
    ordersHandled: 38,
    packagesPicked: 0,
    packagesPacked: 170,
    qcChecks: 0,
    avgProcessingTimeMinutes: 4.4,
    productivityScore: 92,
    attendancePercent: 97,
    currentWorkloadPercent: 80,
    slaContributionPercent: 94,
    performanceStatus: 'EXCELLENT',
    estimatedRevenueSupportedInr: 440000,
    recognitionCategory: 'Most Improved',
    recognitionReason: 'Increased packing speed by 22% over past 30 days following station workflow reorganization.',
    performanceNote: 'Small goods box packer with high precision sealing.'
  },
  // 28. Tarun Bhattacharya (Quality Inspector - On Track)
  {
    id: 'wrk-128',
    workerId: 'EMP-128',
    name: 'Tarun Bhattacharya',
    role: 'Quality Inspector',
    shift: 'Night',
    zone: 'Zone B (Electronics)',
    availability: 'On Shift',
    ordersHandled: 40,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 130,
    avgProcessingTimeMinutes: 4.3,
    productivityScore: 91,
    attendancePercent: 94,
    currentWorkloadPercent: 78,
    slaContributionPercent: 93,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 420000,
    performanceNote: 'Night shift incoming parts inspection lead.'
  },
  // 29. Geeta Pillai (Picker - On Track)
  {
    id: 'wrk-129',
    workerId: 'EMP-129',
    name: 'Geeta Pillai',
    role: 'Picker',
    shift: 'Night',
    zone: 'Zone A (Furniture)',
    availability: 'On Shift',
    ordersHandled: 29,
    packagesPicked: 140,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 5.7,
    productivityScore: 85,
    attendancePercent: 92,
    currentWorkloadPercent: 68,
    slaContributionPercent: 89,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 300000,
    performanceNote: 'Night shift furniture hardware picker.'
  },
  // 30. Alok Tripathy (Warehouse Associate - Available)
  {
    id: 'wrk-130',
    workerId: 'EMP-130',
    name: 'Alok Tripathy',
    role: 'Warehouse Associate',
    shift: 'Morning',
    zone: 'Mezzanine',
    availability: 'Available',
    ordersHandled: 31,
    packagesPicked: 85,
    packagesPacked: 75,
    qcChecks: 15,
    avgProcessingTimeMinutes: 5.6,
    productivityScore: 86,
    attendancePercent: 94,
    currentWorkloadPercent: 62,
    slaContributionPercent: 90,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 310000,
    performanceNote: 'Mezzanine tote consolidation and barcode labeler.'
  },
  // 31. Vinay Hegde (Driver - On Track)
  {
    id: 'wrk-131',
    workerId: 'EMP-131',
    name: 'Vinay Hegde',
    role: 'Driver',
    shift: 'Morning',
    zone: 'Logistics Corridor',
    availability: 'Available',
    ordersHandled: 12,
    packagesPicked: 0,
    packagesPacked: 0,
    qcChecks: 0,
    avgProcessingTimeMinutes: 52.0,
    productivityScore: 88,
    attendancePercent: 93,
    currentWorkloadPercent: 70,
    slaContributionPercent: 91,
    performanceStatus: 'ON TRACK',
    estimatedRevenueSupportedInr: 650000,
    performanceNote: 'Regional intra-city distribution driver.'
  },
  // 32. Sarita Sen (Packer - On Track)
  {
    id: 'wrk-132',
    workerId: 'EMP-132',
    name: 'Sarita Sen',
    role: 'Packer',
    shift: 'Afternoon',
    zone: 'Zone B (Electronics)',
    availability: 'On Shift',
    ordersHandled: 37,
    packagesPicked: 0,
    packagesPacked: 165,
    qcChecks: 0,
    avgProcessingTimeMinutes: 4.6,
    productivityScore: 91,
    attendancePercent: 96,
    currentWorkloadPercent: 80,
    slaContributionPercent: 94,
    performanceStatus: 'GOOD',
    estimatedRevenueSupportedInr: 430000,
    performanceNote: 'Afternoon consumer electronics packing station operator.'
  }
];

export interface MonthlyWorkforceRecord {
  month: string;
  totalWorkers: number;
  activeWorkers: number;
  totalShifts: number;
  attendancePercent: number;
  ordersSupported: number;
  packagesPicked: number;
  packagesPacked: number;
  qcChecks: number;
  dispatchesSupported: number;
  avgProductivity: number;
  slaCompliancePercent: number;
  estimatedRevenueSupportedInr: number;
  overtimeHours: number;
  trainingRecommendationsCount: number;
}

export const MONTHLY_WORKFORCE_HISTORY: MonthlyWorkforceRecord[] = [
  {
    month: 'February 2026 (Current Month)',
    totalWorkers: 32,
    activeWorkers: 30,
    totalShifts: 84,
    attendancePercent: 95.8,
    ordersSupported: 1842,
    packagesPicked: 4120,
    packagesPacked: 3980,
    qcChecks: 880,
    dispatchesSupported: 1740,
    avgProductivity: 92.4,
    slaCompliancePercent: 96.8,
    estimatedRevenueSupportedInr: 16200000,
    overtimeHours: 42,
    trainingRecommendationsCount: 2
  },
  {
    month: 'January 2026',
    totalWorkers: 30,
    activeWorkers: 28,
    totalShifts: 80,
    attendancePercent: 94.2,
    ordersSupported: 1710,
    packagesPicked: 3850,
    packagesPacked: 3720,
    qcChecks: 820,
    dispatchesSupported: 1630,
    avgProductivity: 89.8,
    slaCompliancePercent: 94.1,
    estimatedRevenueSupportedInr: 14500000,
    overtimeHours: 58,
    trainingRecommendationsCount: 4
  },
  {
    month: 'December 2025',
    totalWorkers: 30,
    activeWorkers: 29,
    totalShifts: 82,
    attendancePercent: 93.5,
    ordersSupported: 1950,
    packagesPicked: 4400,
    packagesPacked: 4250,
    qcChecks: 940,
    dispatchesSupported: 1890,
    avgProductivity: 91.2,
    slaCompliancePercent: 95.0,
    estimatedRevenueSupportedInr: 17800000,
    overtimeHours: 74,
    trainingRecommendationsCount: 3
  },
  {
    month: 'November 2025',
    totalWorkers: 28,
    activeWorkers: 27,
    totalShifts: 76,
    attendancePercent: 96.1,
    ordersSupported: 1620,
    packagesPicked: 3600,
    packagesPacked: 3510,
    qcChecks: 780,
    dispatchesSupported: 1580,
    avgProductivity: 90.4,
    slaCompliancePercent: 95.6,
    estimatedRevenueSupportedInr: 13900000,
    overtimeHours: 36,
    trainingRecommendationsCount: 2
  }
];
